export const genData = {
    LGE20KVA: {
      assetId: 120720,
      price: BigInt(15400),
      panel: {
        standard: { label: "120v Split Phase @60Hz", price: BigInt(0) },
        customized: { label: "Customize", price: BigInt(1_100) },
      },
      gridTie: {
        standard: { label: "Stand Alone", price: BigInt(0) },
        Rating225: { label: "Grid Tie (225amp Rating)", price: BigInt(3_850) },
        Rating400: { label: "Grid Tie (400amp Rating)", price: BigInt(5_500) },
        Rating630: { label: "Grid Tie (630amp Rating)", price: BigInt(11_000) },
      },
      monitoring: {
        standard: { label: "No Monitoring", price: BigInt(0) },
        customized: { label: "Monitoring", price: BigInt(2_200) },
      },
      countries: {
        // ==========================================
        // REGION 0: NORTH AMERICA ($180)
        // ==========================================
        "United States of America": BigInt(180),
        "Canada": BigInt(180),
        "Mexico": BigInt(180),
        "Puerto Rico": BigInt(180),
        "Anguilla": BigInt(180),
        "Antigua and Barbuda": BigInt(180),
        "Aruba": BigInt(180),
        "Bahamas": BigInt(180),
        "Barbados": BigInt(180),
        "Belize": BigInt(180),
        "Bermuda": BigInt(180),
        "Bonaire, Sint Eustatius and Saba": BigInt(180),
        "Cayman Islands": BigInt(180),
        "Costa Rica": BigInt(180),
        "Cuba": BigInt(180),
        "Curaçao": BigInt(180),
        "Dominica": BigInt(180),
        "Dominican Republic": BigInt(180),
        "El Salvador": BigInt(180),
        "Grenada": BigInt(180),
        "Guadeloupe": BigInt(180),
        "Guatemala": BigInt(180),
        "Haiti": BigInt(180),
        "Honduras": BigInt(180),
        "Jamaica": BigInt(180),
        "Saint Kitts and Nevis": BigInt(180),
        "Saint Lucia": BigInt(180),
        "Martinique": BigInt(180),
        "Montserrat": BigInt(180),
        "Nicaragua": BigInt(180),
        "Panama": BigInt(180),
        "Saint Barthélemy": BigInt(180),
        "Saint Martin (French part)": BigInt(180),
        "Saint Pierre and Miquelon": BigInt(180),
        "Saint Vincent and the Grenadines": BigInt(180),
        "Sint Maarten (Dutch part)": BigInt(180),
        "Trinidad and Tobago": BigInt(180),
        "Turks and Caicos Islands": BigInt(180),
        "Virgin Islands (British)": BigInt(180),
        "Virgin Islands (U.S.)": BigInt(180),

        // ==========================================
        // REGION 1: SOUTH AMERICA ($250)
        // ==========================================
        "Argentina": BigInt(250),
        "Bolivia": BigInt(250),
        "Brazil": BigInt(250),
        "Chile": BigInt(250),
        "Colombia": BigInt(250),
        "Ecuador": BigInt(250),
        "Falkland Islands": BigInt(250),
        "French Guiana": BigInt(250),
        "South Georgia and the South Sandwich Islands": BigInt(250),
        "Guyana": BigInt(250),
        "Paraguay": BigInt(250),
        "Peru": BigInt(250),
        "Suriname": BigInt(250),
        "Uruguay": BigInt(250),
        "Venezuela": BigInt(250),

        // ==========================================
        // REGION 2: EUROPE ($220)
        // ==========================================
        "Åland Islands": BigInt(220),
        "Albania": BigInt(220),
        "Andorra": BigInt(220),
        "Armenia": BigInt(220),
        "Austria": BigInt(220),
        "Azerbaijan": BigInt(220),
        "Belarus": BigInt(220),
        "Belgium": BigInt(220),
        "Bosnia and Herzegovina": BigInt(220),
        "Bulgaria": BigInt(220),
        "Croatia": BigInt(220),
        "Cyprus": BigInt(220),
        "Czechia": BigInt(220),
        "Denmark": BigInt(220),
        "Estonia": BigInt(220),
        "Faroe Islands": BigInt(220),
        "Finland": BigInt(220),
        "France": BigInt(220),
        "Georgia": BigInt(220),
        "Germany": BigInt(220),
        "Gibraltar": BigInt(220),
        "Greece": BigInt(220),
        "Greenland": BigInt(220),
        "Hungary": BigInt(220),
        "Iceland": BigInt(220),
        "Italy": BigInt(220),
        "Latvia": BigInt(220),
        "Liechtenstein": BigInt(220),
        "Lithuania": BigInt(220),
        "Luxembourg": BigInt(220),
        "North Macedonia": BigInt(220),
        "Malta": BigInt(220),
        "Moldova": BigInt(220),
        "Monaco": BigInt(220),
        "Montenegro": BigInt(220),
        "Netherlands": BigInt(220),
        "Norway": BigInt(220),
        "Poland": BigInt(220),
        "Portugal": BigInt(220),
        "Romania": BigInt(220),
        "Russia": BigInt(220),
        "San Marino": BigInt(220),
        "Serbia": BigInt(220),
        "Slovakia": BigInt(220),
        "Slovenia": BigInt(220),
        "Spain": BigInt(220),
        "Svalbard and Jan Mayen": BigInt(220),
        "Sweden": BigInt(220),
        "Switzerland": BigInt(220),
        "Turkey": BigInt(220),
        "Ukraine": BigInt(220),
        "Holy See (Vatican City)": BigInt(220),

        // ==========================================
        // REGION 3: UK & IRELAND ($230)
        // ==========================================
        "United Kingdom": BigInt(230),
        "Ireland": BigInt(230),
        "Guernsey": BigInt(230),
        "Isle of Man": BigInt(230),
        "Jersey": BigInt(230),

        // ==========================================
        // REGION 4: ASIA PACIFIC ($260)
        // ==========================================
        "Afghanistan": BigInt(260),
        "Bangladesh": BigInt(260),
        "Bhutan": BigInt(260),
        "British Indian Ocean Territory": BigInt(260),
        "Brunei Darussalam": BigInt(260),
        "Cambodia": BigInt(260),
        "Christmas Island": BigInt(260),
        "Cocos (Keeling) Islands": BigInt(260),
        "India": BigInt(260),
        "Indonesia": BigInt(260),
        "Japan": BigInt(260),
        "Kazakhstan": BigInt(260),
        "Kyrgyzstan": BigInt(260),
        "Laos": BigInt(260),
        "Malaysia": BigInt(260),
        "Maldives": BigInt(260),
        "Mongolia": BigInt(260),
        "Myanmar": BigInt(260),
        "Nepal": BigInt(260),
        "Pakistan": BigInt(260),
        "Philippines": BigInt(260),
        "Singapore": BigInt(260),
        "Sri Lanka": BigInt(260),
        "Taiwan": BigInt(260),
        "Tajikistan": BigInt(260),
        "Thailand": BigInt(260),
        "Timor-Leste": BigInt(260),
        "Turkmenistan": BigInt(260),
        "Uzbekistan": BigInt(260),
        "Vietnam": BigInt(260),

        // ==========================================
        // REGION 5: CHINA ($210)
        // ==========================================
        "China": BigInt(210),
        "Hong Kong": BigInt(210),
        "Macao": BigInt(210),

        // ==========================================
        // REGION 6: AUSTRALIA & NEW ZEALAND ($280)
        // ==========================================
        "Australia": BigInt(280),
        "New Zealand": BigInt(280),
        "American Samoa": BigInt(280),
        "Cook Islands": BigInt(280),
        "Fiji": BigInt(210), // Preserved original custom rate baseline override
        "French Polynesia": BigInt(280),
        "Guam": BigInt(280),
        "Heard Island and McDonald Islands": BigInt(280),
        "Kiribati": BigInt(280),
        "Marshall Islands": BigInt(280),
        "Micronesia": BigInt(280),
        "Nauru": BigInt(280),
        "New Caledonia": BigInt(280),
        "Niue": BigInt(280),
        "Norfolk Island": BigInt(280),
        "Northern Mariana Islands": BigInt(280),
        "Palau": BigInt(280),
        "Papua New Guinea": BigInt(280),
        "Pitcairn": BigInt(280),
        "Samoa": BigInt(210), // Preserved original custom rate baseline override
        "Solomon Islands": BigInt(280),
        "Tokelau": BigInt(280),
        "Tonga": BigInt(280),
        "Tuvalu": BigInt(280),
        "United States Minor Outlying Islands": BigInt(280),
        "Vanuatu": BigInt(280),
        "Wallis and Futuna": BigInt(280),

        // ==========================================
        // REGION 7: MIDDLE EAST ($300)
        // ==========================================
        "Bahrain": BigInt(300),
        "Iran": BigInt(300),
        "Iraq": BigInt(300),
        "Israel": BigInt(300),
        "Jordan": BigInt(300),
        "Kuwait": BigInt(300),
        "Lebanon": BigInt(300),
        "Oman": BigInt(300),
        "Palestine, State of": BigInt(300),
        "Qatar": BigInt(300),
        "Saudi Arabia": BigInt(300),
        "Syrian Arab Republic": BigInt(300),
        "United Arab Emirates": BigInt(300),
        "Yemen": BigInt(300),

        // ==========================================
        // REGION 8: AFRICA ($350)
        // ==========================================
        "Algeria": BigInt(350),
        "Angola": BigInt(350),
        "Antarctica": BigInt(350),
        "Benin": BigInt(350),
        "Botswana": BigInt(350),
        "Bouvet Island": BigInt(350),
        "Burkina Faso": BigInt(350),
        "Burundi": BigInt(350),
        "Cabo Verde": BigInt(350),
        "Cameroon": BigInt(350),
        "Central African Republic": BigInt(350),
        "Chad": BigInt(350),
        "Comoros": BigInt(350),
        "Congo, Democratic Republic of the": BigInt(350),
        "Congo, Republic of": BigInt(350),
        "Côte d'Ivoire": BigInt(350),
        "Djibouti": BigInt(350),
        "Egypt": BigInt(350),
        "Equatorial Guinea": BigInt(350),
        "Eritrea": BigInt(350),
        "Eswatini": BigInt(350),
        "Ethiopia": BigInt(350),
        "French Southern Territories": BigInt(350),
        "Gabon": BigInt(350),
        "Gambia": BigInt(350),
        "Ghana": BigInt(350),
        "Guinea": BigInt(350),
        "Guinea-Bissau": BigInt(350),
        "Kenya": BigInt(350),
        "Lesotho": BigInt(350),
        "Liberia": BigInt(350),
        "Libya": BigInt(350),
        "Madagascar": BigInt(350),
        "Malawi": BigInt(350),
        "Mali": BigInt(350),
        "Mauritania": BigInt(350),
        "Mauritius": BigInt(350),
        "Mayotte": BigInt(350),
        "Morocco": BigInt(350),
        "Mozambique": BigInt(350),
        "Namibia": BigInt(350),
        "Niger": BigInt(350),
        "Nigeria": BigInt(350),
        "Réunion": BigInt(350),
        "Rwanda": BigInt(350),
        "Saint Helena, Ascension and Tristan da Cunha": BigInt(350),
        "São Tomé and Príncipe": BigInt(350),
        "Senegal": BigInt(350),
        "Seychelles": BigInt(350),
        "Sierra Leone": BigInt(350),
        "Somalia": BigInt(350),
        "South Africa": BigInt(350),
        "South Sudan": BigInt(350),
        "Sudan": BigInt(350),
        "Tanzania": BigInt(350),
        "Togo": BigInt(350),
        "Tunisia": BigInt(350),
        "Uganda": BigInt(350),
        "Western Sahara": BigInt(350),
        "Zambia": BigInt(350),
        "Zimbabwe": BigInt(350)
      },
      baseDays: 90,
    },
    LGE45KVA: {
      assetId: 120745,
      price: BigInt(16500),
      panel: {
        standard: { label: "120v Split Phase @60Hz", price: BigInt(0) },
        customized: { label: "Customize", price: BigInt(1_100) },
      },
      gridTie: {
        standard: { label: "Stand Alone", price: BigInt(0) },
        Rating225: { label: "Grid Tie (225amp Rating)", price: BigInt(3_850) },
        Rating400: { label: "Grid Tie (400amp Rating)", price: BigInt(5_500) },
        Rating630: { label: "Grid Tie (630amp Rating)", price: BigInt(11_000) },
      },
      monitoring: {
        standard: { label: "No Monitoring", price: BigInt(0) },
        customized: { label: "Monitoring", price: BigInt(2_200) },
      },
      countries: {
        // ==========================================
        // REGION 0: NORTH AMERICA ($180)
        // ==========================================
        "United States of America": BigInt(180),
        "Canada": BigInt(180),
        "Mexico": BigInt(180),
        "Puerto Rico": BigInt(180),
        "Anguilla": BigInt(180),
        "Antigua and Barbuda": BigInt(180),
        "Aruba": BigInt(180),
        "Bahamas": BigInt(180),
        "Barbados": BigInt(180),
        "Belize": BigInt(180),
        "Bermuda": BigInt(180),
        "Bonaire, Sint Eustatius and Saba": BigInt(180),
        "Cayman Islands": BigInt(180),
        "Costa Rica": BigInt(180),
        "Cuba": BigInt(180),
        "Curaçao": BigInt(180),
        "Dominica": BigInt(180),
        "Dominican Republic": BigInt(180),
        "El Salvador": BigInt(180),
        "Grenada": BigInt(180),
        "Guadeloupe": BigInt(180),
        "Guatemala": BigInt(180),
        "Haiti": BigInt(180),
        "Honduras": BigInt(180),
        "Jamaica": BigInt(180),
        "Saint Kitts and Nevis": BigInt(180),
        "Saint Lucia": BigInt(180),
        "Martinique": BigInt(180),
        "Montserrat": BigInt(180),
        "Nicaragua": BigInt(180),
        "Panama": BigInt(180),
        "Saint Barthélemy": BigInt(180),
        "Saint Martin (French part)": BigInt(180),
        "Saint Pierre and Miquelon": BigInt(180),
        "Saint Vincent and the Grenadines": BigInt(180),
        "Sint Maarten (Dutch part)": BigInt(180),
        "Trinidad and Tobago": BigInt(180),
        "Turks and Caicos Islands": BigInt(180),
        "Virgin Islands (British)": BigInt(180),
        "Virgin Islands (U.S.)": BigInt(180),

        // ==========================================
        // REGION 1: SOUTH AMERICA ($250)
        // ==========================================
        "Argentina": BigInt(250),
        "Bolivia": BigInt(250),
        "Brazil": BigInt(250),
        "Chile": BigInt(250),
        "Colombia": BigInt(250),
        "Ecuador": BigInt(250),
        "Falkland Islands": BigInt(250),
        "French Guiana": BigInt(250),
        "South Georgia and the South Sandwich Islands": BigInt(250),
        "Guyana": BigInt(250),
        "Paraguay": BigInt(250),
        "Peru": BigInt(250),
        "Suriname": BigInt(250),
        "Uruguay": BigInt(250),
        "Venezuela": BigInt(250),

        // ==========================================
        // REGION 2: EUROPE ($220)
        // ==========================================
        "Åland Islands": BigInt(220),
        "Albania": BigInt(220),
        "Andorra": BigInt(220),
        "Armenia": BigInt(220),
        "Austria": BigInt(220),
        "Azerbaijan": BigInt(220),
        "Belarus": BigInt(220),
        "Belgium": BigInt(220),
        "Bosnia and Herzegovina": BigInt(220),
        "Bulgaria": BigInt(220),
        "Croatia": BigInt(220),
        "Cyprus": BigInt(220),
        "Czechia": BigInt(220),
        "Denmark": BigInt(220),
        "Estonia": BigInt(220),
        "Faroe Islands": BigInt(220),
        "Finland": BigInt(220),
        "France": BigInt(220),
        "Georgia": BigInt(220),
        "Germany": BigInt(220),
        "Gibraltar": BigInt(220),
        "Greece": BigInt(220),
        "Greenland": BigInt(220),
        "Hungary": BigInt(220),
        "Iceland": BigInt(220),
        "Italy": BigInt(220),
        "Latvia": BigInt(220),
        "Liechtenstein": BigInt(220),
        "Lithuania": BigInt(220),
        "Luxembourg": BigInt(220),
        "North Macedonia": BigInt(220),
        "Malta": BigInt(220),
        "Moldova": BigInt(220),
        "Monaco": BigInt(220),
        "Montenegro": BigInt(220),
        "Netherlands": BigInt(220),
        "Norway": BigInt(220),
        "Poland": BigInt(220),
        "Portugal": BigInt(220),
        "Romania": BigInt(220),
        "Russia": BigInt(220),
        "San Marino": BigInt(220),
        "Serbia": BigInt(220),
        "Slovakia": BigInt(220),
        "Slovenia": BigInt(220),
        "Spain": BigInt(220),
        "Svalbard and Jan Mayen": BigInt(220),
        "Sweden": BigInt(220),
        "Switzerland": BigInt(220),
        "Turkey": BigInt(220),
        "Ukraine": BigInt(220),
        "Holy See (Vatican City)": BigInt(220),

        // ==========================================
        // REGION 3: UK & IRELAND ($230)
        // ==========================================
        "United Kingdom": BigInt(230),
        "Ireland": BigInt(230),
        "Guernsey": BigInt(230),
        "Isle of Man": BigInt(230),
        "Jersey": BigInt(230),

        // ==========================================
        // REGION 4: ASIA PACIFIC ($260)
        // ==========================================
        "Afghanistan": BigInt(260),
        "Bangladesh": BigInt(260),
        "Bhutan": BigInt(260),
        "British Indian Ocean Territory": BigInt(260),
        "Brunei Darussalam": BigInt(260),
        "Cambodia": BigInt(260),
        "Christmas Island": BigInt(260),
        "Cocos (Keeling) Islands": BigInt(260),
        "India": BigInt(260),
        "Indonesia": BigInt(260),
        "Japan": BigInt(260),
        "Kazakhstan": BigInt(260),
        "Kyrgyzstan": BigInt(260),
        "Laos": BigInt(260),
        "Malaysia": BigInt(260),
        "Maldives": BigInt(260),
        "Mongolia": BigInt(260),
        "Myanmar": BigInt(260),
        "Nepal": BigInt(260),
        "Pakistan": BigInt(260),
        "Philippines": BigInt(260),
        "Singapore": BigInt(260),
        "Sri Lanka": BigInt(260),
        "Taiwan": BigInt(260),
        "Tajikistan": BigInt(260),
        "Thailand": BigInt(260),
        "Timor-Leste": BigInt(260),
        "Turkmenistan": BigInt(260),
        "Uzbekistan": BigInt(260),
        "Vietnam": BigInt(260),

        // ==========================================
        // REGION 5: CHINA ($210)
        // ==========================================
        "China": BigInt(210),
        "Hong Kong": BigInt(210),
        "Macao": BigInt(210),

        // ==========================================
        // REGION 6: AUSTRALIA & NEW ZEALAND ($280)
        // ==========================================
        "Australia": BigInt(280),
        "New Zealand": BigInt(280),
        "American Samoa": BigInt(280),
        "Cook Islands": BigInt(280),
        "Fiji": BigInt(210), // Preserved original custom rate baseline override
        "French Polynesia": BigInt(280),
        "Guam": BigInt(280),
        "Heard Island and McDonald Islands": BigInt(280),
        "Kiribati": BigInt(280),
        "Marshall Islands": BigInt(280),
        "Micronesia": BigInt(280),
        "Nauru": BigInt(280),
        "New Caledonia": BigInt(280),
        "Niue": BigInt(280),
        "Norfolk Island": BigInt(280),
        "Northern Mariana Islands": BigInt(280),
        "Palau": BigInt(280),
        "Papua New Guinea": BigInt(280),
        "Pitcairn": BigInt(280),
        "Samoa": BigInt(210), // Preserved original custom rate baseline override
        "Solomon Islands": BigInt(280),
        "Tokelau": BigInt(280),
        "Tonga": BigInt(280),
        "Tuvalu": BigInt(280),
        "United States Minor Outlying Islands": BigInt(280),
        "Vanuatu": BigInt(280),
        "Wallis and Futuna": BigInt(280),

        // ==========================================
        // REGION 7: MIDDLE EAST ($300)
        // ==========================================
        "Bahrain": BigInt(300),
        "Iran": BigInt(300),
        "Iraq": BigInt(300),
        "Israel": BigInt(300),
        "Jordan": BigInt(300),
        "Kuwait": BigInt(300),
        "Lebanon": BigInt(300),
        "Oman": BigInt(300),
        "Palestine, State of": BigInt(300),
        "Qatar": BigInt(300),
        "Saudi Arabia": BigInt(300),
        "Syrian Arab Republic": BigInt(300),
        "United Arab Emirates": BigInt(300),
        "Yemen": BigInt(300),

        // ==========================================
        // REGION 8: AFRICA ($350)
        // ==========================================
        "Algeria": BigInt(350),
        "Angola": BigInt(350),
        "Antarctica": BigInt(350),
        "Benin": BigInt(350),
        "Botswana": BigInt(350),
        "Bouvet Island": BigInt(350),
        "Burkina Faso": BigInt(350),
        "Burundi": BigInt(350),
        "Cabo Verde": BigInt(350),
        "Cameroon": BigInt(350),
        "Central African Republic": BigInt(350),
        "Chad": BigInt(350),
        "Comoros": BigInt(350),
        "Congo, Democratic Republic of the": BigInt(350),
        "Congo, Republic of": BigInt(350),
        "Côte d'Ivoire": BigInt(350),
        "Djibouti": BigInt(350),
        "Egypt": BigInt(350),
        "Equatorial Guinea": BigInt(350),
        "Eritrea": BigInt(350),
        "Eswatini": BigInt(350),
        "Ethiopia": BigInt(350),
        "French Southern Territories": BigInt(350),
        "Gabon": BigInt(350),
        "Gambia": BigInt(350),
        "Ghana": BigInt(350),
        "Guinea": BigInt(350),
        "Guinea-Bissau": BigInt(350),
        "Kenya": BigInt(350),
        "Lesotho": BigInt(350),
        "Liberia": BigInt(350),
        "Libya": BigInt(350),
        "Madagascar": BigInt(350),
        "Malawi": BigInt(350),
        "Mali": BigInt(350),
        "Mauritania": BigInt(350),
        "Mauritius": BigInt(350),
        "Mayotte": BigInt(350),
        "Morocco": BigInt(350),
        "Mozambique": BigInt(350),
        "Namibia": BigInt(350),
        "Niger": BigInt(350),
        "Nigeria": BigInt(350),
        "Réunion": BigInt(350),
        "Rwanda": BigInt(350),
        "Saint Helena, Ascension and Tristan da Cunha": BigInt(350),
        "São Tomé and Príncipe": BigInt(350),
        "Senegal": BigInt(350),
        "Seychelles": BigInt(350),
        "Sierra Leone": BigInt(350),
        "Somalia": BigInt(350),
        "South Africa": BigInt(350),
        "South Sudan": BigInt(350),
        "Sudan": BigInt(350),
        "Tanzania": BigInt(350),
        "Togo": BigInt(350),
        "Tunisia": BigInt(350),
        "Uganda": BigInt(350),
        "Western Sahara": BigInt(350),
        "Zambia": BigInt(350),
        "Zimbabwe": BigInt(350)
      },
      baseDays: 90,
    },
    LGE70KVA: {
      assetId: 120770,
      price: BigInt(17600),
      panel: {
        standard: { label: "120v Split Phase @60Hz", price: BigInt(0) },
        customized: { label: "Customize", price: BigInt(1_100) },
      },
      gridTie: {
        standard: { label: "Stand Alone", price: BigInt(0) },
        Rating225: { label: "Grid Tie (225amp Rating)", price: BigInt(3_850) },
        Rating400: { label: "Grid Tie (400amp Rating)", price: BigInt(5_500) },
        Rating630: { label: "Grid Tie (630amp Rating)", price: BigInt(11_000) },
      },
      monitoring: {
        standard: { label: "No Monitoring", price: BigInt(0) },
        customized: { label: "Monitoring", price: BigInt(2_200) },
      },
      countries: {
        // ==========================================
        // REGION 0: NORTH AMERICA ($180)
        // ==========================================
        "United States of America": BigInt(180),
        "Canada": BigInt(180),
        "Mexico": BigInt(180),
        "Puerto Rico": BigInt(180),
        "Anguilla": BigInt(180),
        "Antigua and Barbuda": BigInt(180),
        "Aruba": BigInt(180),
        "Bahamas": BigInt(180),
        "Barbados": BigInt(180),
        "Belize": BigInt(180),
        "Bermuda": BigInt(180),
        "Bonaire, Sint Eustatius and Saba": BigInt(180),
        "Cayman Islands": BigInt(180),
        "Costa Rica": BigInt(180),
        "Cuba": BigInt(180),
        "Curaçao": BigInt(180),
        "Dominica": BigInt(180),
        "Dominican Republic": BigInt(180),
        "El Salvador": BigInt(180),
        "Grenada": BigInt(180),
        "Guadeloupe": BigInt(180),
        "Guatemala": BigInt(180),
        "Haiti": BigInt(180),
        "Honduras": BigInt(180),
        "Jamaica": BigInt(180),
        "Saint Kitts and Nevis": BigInt(180),
        "Saint Lucia": BigInt(180),
        "Martinique": BigInt(180),
        "Montserrat": BigInt(180),
        "Nicaragua": BigInt(180),
        "Panama": BigInt(180),
        "Saint Barthélemy": BigInt(180),
        "Saint Martin (French part)": BigInt(180),
        "Saint Pierre and Miquelon": BigInt(180),
        "Saint Vincent and the Grenadines": BigInt(180),
        "Sint Maarten (Dutch part)": BigInt(180),
        "Trinidad and Tobago": BigInt(180),
        "Turks and Caicos Islands": BigInt(180),
        "Virgin Islands (British)": BigInt(180),
        "Virgin Islands (U.S.)": BigInt(180),

        // ==========================================
        // REGION 1: SOUTH AMERICA ($250)
        // ==========================================
        "Argentina": BigInt(250),
        "Bolivia": BigInt(250),
        "Brazil": BigInt(250),
        "Chile": BigInt(250),
        "Colombia": BigInt(250),
        "Ecuador": BigInt(250),
        "Falkland Islands": BigInt(250),
        "French Guiana": BigInt(250),
        "South Georgia and the South Sandwich Islands": BigInt(250),
        "Guyana": BigInt(250),
        "Paraguay": BigInt(250),
        "Peru": BigInt(250),
        "Suriname": BigInt(250),
        "Uruguay": BigInt(250),
        "Venezuela": BigInt(250),

        // ==========================================
        // REGION 2: EUROPE ($220)
        // ==========================================
        "Åland Islands": BigInt(220),
        "Albania": BigInt(220),
        "Andorra": BigInt(220),
        "Armenia": BigInt(220),
        "Austria": BigInt(220),
        "Azerbaijan": BigInt(220),
        "Belarus": BigInt(220),
        "Belgium": BigInt(220),
        "Bosnia and Herzegovina": BigInt(220),
        "Bulgaria": BigInt(220),
        "Croatia": BigInt(220),
        "Cyprus": BigInt(220),
        "Czechia": BigInt(220),
        "Denmark": BigInt(220),
        "Estonia": BigInt(220),
        "Faroe Islands": BigInt(220),
        "Finland": BigInt(220),
        "France": BigInt(220),
        "Georgia": BigInt(220),
        "Germany": BigInt(220),
        "Gibraltar": BigInt(220),
        "Greece": BigInt(220),
        "Greenland": BigInt(220),
        "Hungary": BigInt(220),
        "Iceland": BigInt(220),
        "Italy": BigInt(220),
        "Latvia": BigInt(220),
        "Liechtenstein": BigInt(220),
        "Lithuania": BigInt(220),
        "Luxembourg": BigInt(220),
        "North Macedonia": BigInt(220),
        "Malta": BigInt(220),
        "Moldova": BigInt(220),
        "Monaco": BigInt(220),
        "Montenegro": BigInt(220),
        "Netherlands": BigInt(220),
        "Norway": BigInt(220),
        "Poland": BigInt(220),
        "Portugal": BigInt(220),
        "Romania": BigInt(220),
        "Russia": BigInt(220),
        "San Marino": BigInt(220),
        "Serbia": BigInt(220),
        "Slovakia": BigInt(220),
        "Slovenia": BigInt(220),
        "Spain": BigInt(220),
        "Svalbard and Jan Mayen": BigInt(220),
        "Sweden": BigInt(220),
        "Switzerland": BigInt(220),
        "Turkey": BigInt(220),
        "Ukraine": BigInt(220),
        "Holy See (Vatican City)": BigInt(220),

        // ==========================================
        // REGION 3: UK & IRELAND ($230)
        // ==========================================
        "United Kingdom": BigInt(230),
        "Ireland": BigInt(230),
        "Guernsey": BigInt(230),
        "Isle of Man": BigInt(230),
        "Jersey": BigInt(230),

        // ==========================================
        // REGION 4: ASIA PACIFIC ($260)
        // ==========================================
        "Afghanistan": BigInt(260),
        "Bangladesh": BigInt(260),
        "Bhutan": BigInt(260),
        "British Indian Ocean Territory": BigInt(260),
        "Brunei Darussalam": BigInt(260),
        "Cambodia": BigInt(260),
        "Christmas Island": BigInt(260),
        "Cocos (Keeling) Islands": BigInt(260),
        "India": BigInt(260),
        "Indonesia": BigInt(260),
        "Japan": BigInt(260),
        "Kazakhstan": BigInt(260),
        "Kyrgyzstan": BigInt(260),
        "Laos": BigInt(260),
        "Malaysia": BigInt(260),
        "Maldives": BigInt(260),
        "Mongolia": BigInt(260),
        "Myanmar": BigInt(260),
        "Nepal": BigInt(260),
        "Pakistan": BigInt(260),
        "Philippines": BigInt(260),
        "Singapore": BigInt(260),
        "Sri Lanka": BigInt(260),
        "Taiwan": BigInt(260),
        "Tajikistan": BigInt(260),
        "Thailand": BigInt(260),
        "Timor-Leste": BigInt(260),
        "Turkmenistan": BigInt(260),
        "Uzbekistan": BigInt(260),
        "Vietnam": BigInt(260),

        // ==========================================
        // REGION 5: CHINA ($210)
        // ==========================================
        "China": BigInt(210),
        "Hong Kong": BigInt(210),
        "Macao": BigInt(210),

        // ==========================================
        // REGION 6: AUSTRALIA & NEW ZEALAND ($280)
        // ==========================================
        "Australia": BigInt(280),
        "New Zealand": BigInt(280),
        "American Samoa": BigInt(280),
        "Cook Islands": BigInt(280),
        "Fiji": BigInt(210), // Preserved original custom rate baseline override
        "French Polynesia": BigInt(280),
        "Guam": BigInt(280),
        "Heard Island and McDonald Islands": BigInt(280),
        "Kiribati": BigInt(280),
        "Marshall Islands": BigInt(280),
        "Micronesia": BigInt(280),
        "Nauru": BigInt(280),
        "New Caledonia": BigInt(280),
        "Niue": BigInt(280),
        "Norfolk Island": BigInt(280),
        "Northern Mariana Islands": BigInt(280),
        "Palau": BigInt(280),
        "Papua New Guinea": BigInt(280),
        "Pitcairn": BigInt(280),
        "Samoa": BigInt(210), // Preserved original custom rate baseline override
        "Solomon Islands": BigInt(280),
        "Tokelau": BigInt(280),
        "Tonga": BigInt(280),
        "Tuvalu": BigInt(280),
        "United States Minor Outlying Islands": BigInt(280),
        "Vanuatu": BigInt(280),
        "Wallis and Futuna": BigInt(280),

        // ==========================================
        // REGION 7: MIDDLE EAST ($300)
        // ==========================================
        "Bahrain": BigInt(300),
        "Iran": BigInt(300),
        "Iraq": BigInt(300),
        "Israel": BigInt(300),
        "Jordan": BigInt(300),
        "Kuwait": BigInt(300),
        "Lebanon": BigInt(300),
        "Oman": BigInt(300),
        "Palestine, State of": BigInt(300),
        "Qatar": BigInt(300),
        "Saudi Arabia": BigInt(300),
        "Syrian Arab Republic": BigInt(300),
        "United Arab Emirates": BigInt(300),
        "Yemen": BigInt(300),

        // ==========================================
        // REGION 8: AFRICA ($350)
        // ==========================================
        "Algeria": BigInt(350),
        "Angola": BigInt(350),
        "Antarctica": BigInt(350),
        "Benin": BigInt(350),
        "Botswana": BigInt(350),
        "Bouvet Island": BigInt(350),
        "Burkina Faso": BigInt(350),
        "Burundi": BigInt(350),
        "Cabo Verde": BigInt(350),
        "Cameroon": BigInt(350),
        "Central African Republic": BigInt(350),
        "Chad": BigInt(350),
        "Comoros": BigInt(350),
        "Congo, Democratic Republic of the": BigInt(350),
        "Congo, Republic of": BigInt(350),
        "Côte d'Ivoire": BigInt(350),
        "Djibouti": BigInt(350),
        "Egypt": BigInt(350),
        "Equatorial Guinea": BigInt(350),
        "Eritrea": BigInt(350),
        "Eswatini": BigInt(350),
        "Ethiopia": BigInt(350),
        "French Southern Territories": BigInt(350),
        "Gabon": BigInt(350),
        "Gambia": BigInt(350),
        "Ghana": BigInt(350),
        "Guinea": BigInt(350),
        "Guinea-Bissau": BigInt(350),
        "Kenya": BigInt(350),
        "Lesotho": BigInt(350),
        "Liberia": BigInt(350),
        "Libya": BigInt(350),
        "Madagascar": BigInt(350),
        "Malawi": BigInt(350),
        "Mali": BigInt(350),
        "Mauritania": BigInt(350),
        "Mauritius": BigInt(350),
        "Mayotte": BigInt(350),
        "Morocco": BigInt(350),
        "Mozambique": BigInt(350),
        "Namibia": BigInt(350),
        "Niger": BigInt(350),
        "Nigeria": BigInt(350),
        "Réunion": BigInt(350),
        "Rwanda": BigInt(350),
        "Saint Helena, Ascension and Tristan da Cunha": BigInt(350),
        "São Tomé and Príncipe": BigInt(350),
        "Senegal": BigInt(350),
        "Seychelles": BigInt(350),
        "Sierra Leone": BigInt(350),
        "Somalia": BigInt(350),
        "South Africa": BigInt(350),
        "South Sudan": BigInt(350),
        "Sudan": BigInt(350),
        "Tanzania": BigInt(350),
        "Togo": BigInt(350),
        "Tunisia": BigInt(350),
        "Uganda": BigInt(350),
        "Western Sahara": BigInt(350),
        "Zambia": BigInt(350),
        "Zimbabwe": BigInt(350)
      },
      baseDays: 90,
    },
    LGX100KVA: {
      assetId: 1207100,
      price: BigInt(47300),
      panel: {
        standard: { label: "480v 3-Phase @60Hz", price: BigInt(0) },
        customized: { label: "Customize", price: BigInt(1_100) },
      },
      gridTie: {
        standard: { label: "Stand Alone", price: BigInt(0) },
        Rating400: { label: "Grid Tie (400amp Rating)", price: BigInt(5_500) },
        Rating1260: { label: "Grid Tie (1260amp Rating)", price: BigInt(22_000) },
        Rating2100: { label: "Grid Tie (2100amp Rating)", price: BigInt(30_800) },
      },
      monitoring: {
        standard: { label: "No Monitoring", price: BigInt(0) },
        customized: { label: "Monitoring", price: BigInt(2_200) },
      },
      countries: {
        // ==========================================
        // REGION 0: NORTH AMERICA ($180)
        // ==========================================
        "United States of America": BigInt(180),
        "Canada": BigInt(180),
        "Mexico": BigInt(180),
        "Puerto Rico": BigInt(180),
        "Anguilla": BigInt(180),
        "Antigua and Barbuda": BigInt(180),
        "Aruba": BigInt(180),
        "Bahamas": BigInt(180),
        "Barbados": BigInt(180),
        "Belize": BigInt(180),
        "Bermuda": BigInt(180),
        "Bonaire, Sint Eustatius and Saba": BigInt(180),
        "Cayman Islands": BigInt(180),
        "Costa Rica": BigInt(180),
        "Cuba": BigInt(180),
        "Curaçao": BigInt(180),
        "Dominica": BigInt(180),
        "Dominican Republic": BigInt(180),
        "El Salvador": BigInt(180),
        "Grenada": BigInt(180),
        "Guadeloupe": BigInt(180),
        "Guatemala": BigInt(180),
        "Haiti": BigInt(180),
        "Honduras": BigInt(180),
        "Jamaica": BigInt(180),
        "Saint Kitts and Nevis": BigInt(180),
        "Saint Lucia": BigInt(180),
        "Martinique": BigInt(180),
        "Montserrat": BigInt(180),
        "Nicaragua": BigInt(180),
        "Panama": BigInt(180),
        "Saint Barthélemy": BigInt(180),
        "Saint Martin (French part)": BigInt(180),
        "Saint Pierre and Miquelon": BigInt(180),
        "Saint Vincent and the Grenadines": BigInt(180),
        "Sint Maarten (Dutch part)": BigInt(180),
        "Trinidad and Tobago": BigInt(180),
        "Turks and Caicos Islands": BigInt(180),
        "Virgin Islands (British)": BigInt(180),
        "Virgin Islands (U.S.)": BigInt(180),

        // ==========================================
        // REGION 1: SOUTH AMERICA ($250)
        // ==========================================
        "Argentina": BigInt(250),
        "Bolivia": BigInt(250),
        "Brazil": BigInt(250),
        "Chile": BigInt(250),
        "Colombia": BigInt(250),
        "Ecuador": BigInt(250),
        "Falkland Islands": BigInt(250),
        "French Guiana": BigInt(250),
        "South Georgia and the South Sandwich Islands": BigInt(250),
        "Guyana": BigInt(250),
        "Paraguay": BigInt(250),
        "Peru": BigInt(250),
        "Suriname": BigInt(250),
        "Uruguay": BigInt(250),
        "Venezuela": BigInt(250),

        // ==========================================
        // REGION 2: EUROPE ($220)
        // ==========================================
        "Åland Islands": BigInt(220),
        "Albania": BigInt(220),
        "Andorra": BigInt(220),
        "Armenia": BigInt(220),
        "Austria": BigInt(220),
        "Azerbaijan": BigInt(220),
        "Belarus": BigInt(220),
        "Belgium": BigInt(220),
        "Bosnia and Herzegovina": BigInt(220),
        "Bulgaria": BigInt(220),
        "Croatia": BigInt(220),
        "Cyprus": BigInt(220),
        "Czechia": BigInt(220),
        "Denmark": BigInt(220),
        "Estonia": BigInt(220),
        "Faroe Islands": BigInt(220),
        "Finland": BigInt(220),
        "France": BigInt(220),
        "Georgia": BigInt(220),
        "Germany": BigInt(220),
        "Gibraltar": BigInt(220),
        "Greece": BigInt(220),
        "Greenland": BigInt(220),
        "Hungary": BigInt(220),
        "Iceland": BigInt(220),
        "Italy": BigInt(220),
        "Latvia": BigInt(220),
        "Liechtenstein": BigInt(220),
        "Lithuania": BigInt(220),
        "Luxembourg": BigInt(220),
        "North Macedonia": BigInt(220),
        "Malta": BigInt(220),
        "Moldova": BigInt(220),
        "Monaco": BigInt(220),
        "Montenegro": BigInt(220),
        "Netherlands": BigInt(220),
        "Norway": BigInt(220),
        "Poland": BigInt(220),
        "Portugal": BigInt(220),
        "Romania": BigInt(220),
        "Russia": BigInt(220),
        "San Marino": BigInt(220),
        "Serbia": BigInt(220),
        "Slovakia": BigInt(220),
        "Slovenia": BigInt(220),
        "Spain": BigInt(220),
        "Svalbard and Jan Mayen": BigInt(220),
        "Sweden": BigInt(220),
        "Switzerland": BigInt(220),
        "Turkey": BigInt(220),
        "Ukraine": BigInt(220),
        "Holy See (Vatican City)": BigInt(220),

        // ==========================================
        // REGION 3: UK & IRELAND ($230)
        // ==========================================
        "United Kingdom": BigInt(230),
        "Ireland": BigInt(230),
        "Guernsey": BigInt(230),
        "Isle of Man": BigInt(230),
        "Jersey": BigInt(230),

        // ==========================================
        // REGION 4: ASIA PACIFIC ($260)
        // ==========================================
        "Afghanistan": BigInt(260),
        "Bangladesh": BigInt(260),
        "Bhutan": BigInt(260),
        "British Indian Ocean Territory": BigInt(260),
        "Brunei Darussalam": BigInt(260),
        "Cambodia": BigInt(260),
        "Christmas Island": BigInt(260),
        "Cocos (Keeling) Islands": BigInt(260),
        "India": BigInt(260),
        "Indonesia": BigInt(260),
        "Japan": BigInt(260),
        "Kazakhstan": BigInt(260),
        "Kyrgyzstan": BigInt(260),
        "Laos": BigInt(260),
        "Malaysia": BigInt(260),
        "Maldives": BigInt(260),
        "Mongolia": BigInt(260),
        "Myanmar": BigInt(260),
        "Nepal": BigInt(260),
        "Pakistan": BigInt(260),
        "Philippines": BigInt(260),
        "Singapore": BigInt(260),
        "Sri Lanka": BigInt(260),
        "Taiwan": BigInt(260),
        "Tajikistan": BigInt(260),
        "Thailand": BigInt(260),
        "Timor-Leste": BigInt(260),
        "Turkmenistan": BigInt(260),
        "Uzbekistan": BigInt(260),
        "Vietnam": BigInt(260),

        // ==========================================
        // REGION 5: CHINA ($210)
        // ==========================================
        "China": BigInt(210),
        "Hong Kong": BigInt(210),
        "Macao": BigInt(210),

        // ==========================================
        // REGION 6: AUSTRALIA & NEW ZEALAND ($280)
        // ==========================================
        "Australia": BigInt(280),
        "New Zealand": BigInt(280),
        "American Samoa": BigInt(280),
        "Cook Islands": BigInt(280),
        "Fiji": BigInt(210), // Preserved original custom rate baseline override
        "French Polynesia": BigInt(280),
        "Guam": BigInt(280),
        "Heard Island and McDonald Islands": BigInt(280),
        "Kiribati": BigInt(280),
        "Marshall Islands": BigInt(280),
        "Micronesia": BigInt(280),
        "Nauru": BigInt(280),
        "New Caledonia": BigInt(280),
        "Niue": BigInt(280),
        "Norfolk Island": BigInt(280),
        "Northern Mariana Islands": BigInt(280),
        "Palau": BigInt(280),
        "Papua New Guinea": BigInt(280),
        "Pitcairn": BigInt(280),
        "Samoa": BigInt(210), // Preserved original custom rate baseline override
        "Solomon Islands": BigInt(280),
        "Tokelau": BigInt(280),
        "Tonga": BigInt(280),
        "Tuvalu": BigInt(280),
        "United States Minor Outlying Islands": BigInt(280),
        "Vanuatu": BigInt(280),
        "Wallis and Futuna": BigInt(280),

        // ==========================================
        // REGION 7: MIDDLE EAST ($300)
        // ==========================================
        "Bahrain": BigInt(300),
        "Iran": BigInt(300),
        "Iraq": BigInt(300),
        "Israel": BigInt(300),
        "Jordan": BigInt(300),
        "Kuwait": BigInt(300),
        "Lebanon": BigInt(300),
        "Oman": BigInt(300),
        "Palestine, State of": BigInt(300),
        "Qatar": BigInt(300),
        "Saudi Arabia": BigInt(300),
        "Syrian Arab Republic": BigInt(300),
        "United Arab Emirates": BigInt(300),
        "Yemen": BigInt(300),

        // ==========================================
        // REGION 8: AFRICA ($350)
        // ==========================================
        "Algeria": BigInt(350),
        "Angola": BigInt(350),
        "Antarctica": BigInt(350),
        "Benin": BigInt(350),
        "Botswana": BigInt(350),
        "Bouvet Island": BigInt(350),
        "Burkina Faso": BigInt(350),
        "Burundi": BigInt(350),
        "Cabo Verde": BigInt(350),
        "Cameroon": BigInt(350),
        "Central African Republic": BigInt(350),
        "Chad": BigInt(350),
        "Comoros": BigInt(350),
        "Congo, Democratic Republic of the": BigInt(350),
        "Congo, Republic of": BigInt(350),
        "Côte d'Ivoire": BigInt(350),
        "Djibouti": BigInt(350),
        "Egypt": BigInt(350),
        "Equatorial Guinea": BigInt(350),
        "Eritrea": BigInt(350),
        "Eswatini": BigInt(350),
        "Ethiopia": BigInt(350),
        "French Southern Territories": BigInt(350),
        "Gabon": BigInt(350),
        "Gambia": BigInt(350),
        "Ghana": BigInt(350),
        "Guinea": BigInt(350),
        "Guinea-Bissau": BigInt(350),
        "Kenya": BigInt(350),
        "Lesotho": BigInt(350),
        "Liberia": BigInt(350),
        "Libya": BigInt(350),
        "Madagascar": BigInt(350),
        "Malawi": BigInt(350),
        "Mali": BigInt(350),
        "Mauritania": BigInt(350),
        "Mauritius": BigInt(350),
        "Mayotte": BigInt(350),
        "Morocco": BigInt(350),
        "Mozambique": BigInt(350),
        "Namibia": BigInt(350),
        "Niger": BigInt(350),
        "Nigeria": BigInt(350),
        "Réunion": BigInt(350),
        "Rwanda": BigInt(350),
        "Saint Helena, Ascension and Tristan da Cunha": BigInt(350),
        "São Tomé and Príncipe": BigInt(350),
        "Senegal": BigInt(350),
        "Seychelles": BigInt(350),
        "Sierra Leone": BigInt(350),
        "Somalia": BigInt(350),
        "South Africa": BigInt(350),
        "South Sudan": BigInt(350),
        "Sudan": BigInt(350),
        "Tanzania": BigInt(350),
        "Togo": BigInt(350),
        "Tunisia": BigInt(350),
        "Uganda": BigInt(350),
        "Western Sahara": BigInt(350),
        "Zambia": BigInt(350),
        "Zimbabwe": BigInt(350)
      },
      baseDays: 180,
    },
    LGX200KVA: {
      assetId: 1207200,
      price: BigInt(58300),
      panel: {
        standard: { label: "480v 3-Phase @60Hz", price: BigInt(0) },
        customized: { label: "Customize", price: BigInt(1_100) },
      },
      gridTie: {
        standard: { label: "Stand Alone", price: BigInt(0) },
        Rating400: { label: "Grid Tie (400amp Rating)", price: BigInt(5_500) },
        Rating1260: { label: "Grid Tie (1260amp Rating)", price: BigInt(22_000) },
        Rating2100: { label: "Grid Tie (2100amp Rating)", price: BigInt(30_800) },
      },
      monitoring: {
        standard: { label: "No Monitoring", price: BigInt(0) },
        customized: { label: "Monitoring", price: BigInt(2_200) },
      },
      countries: {
        // ==========================================
        // REGION 0: NORTH AMERICA ($180)
        // ==========================================
        "United States of America": BigInt(180),
        "Canada": BigInt(180),
        "Mexico": BigInt(180),
        "Puerto Rico": BigInt(180),
        "Anguilla": BigInt(180),
        "Antigua and Barbuda": BigInt(180),
        "Aruba": BigInt(180),
        "Bahamas": BigInt(180),
        "Barbados": BigInt(180),
        "Belize": BigInt(180),
        "Bermuda": BigInt(180),
        "Bonaire, Sint Eustatius and Saba": BigInt(180),
        "Cayman Islands": BigInt(180),
        "Costa Rica": BigInt(180),
        "Cuba": BigInt(180),
        "Curaçao": BigInt(180),
        "Dominica": BigInt(180),
        "Dominican Republic": BigInt(180),
        "El Salvador": BigInt(180),
        "Grenada": BigInt(180),
        "Guadeloupe": BigInt(180),
        "Guatemala": BigInt(180),
        "Haiti": BigInt(180),
        "Honduras": BigInt(180),
        "Jamaica": BigInt(180),
        "Saint Kitts and Nevis": BigInt(180),
        "Saint Lucia": BigInt(180),
        "Martinique": BigInt(180),
        "Montserrat": BigInt(180),
        "Nicaragua": BigInt(180),
        "Panama": BigInt(180),
        "Saint Barthélemy": BigInt(180),
        "Saint Martin (French part)": BigInt(180),
        "Saint Pierre and Miquelon": BigInt(180),
        "Saint Vincent and the Grenadines": BigInt(180),
        "Sint Maarten (Dutch part)": BigInt(180),
        "Trinidad and Tobago": BigInt(180),
        "Turks and Caicos Islands": BigInt(180),
        "Virgin Islands (British)": BigInt(180),
        "Virgin Islands (U.S.)": BigInt(180),

        // ==========================================
        // REGION 1: SOUTH AMERICA ($250)
        // ==========================================
        "Argentina": BigInt(250),
        "Bolivia": BigInt(250),
        "Brazil": BigInt(250),
        "Chile": BigInt(250),
        "Colombia": BigInt(250),
        "Ecuador": BigInt(250),
        "Falkland Islands": BigInt(250),
        "French Guiana": BigInt(250),
        "South Georgia and the South Sandwich Islands": BigInt(250),
        "Guyana": BigInt(250),
        "Paraguay": BigInt(250),
        "Peru": BigInt(250),
        "Suriname": BigInt(250),
        "Uruguay": BigInt(250),
        "Venezuela": BigInt(250),

        // ==========================================
        // REGION 2: EUROPE ($220)
        // ==========================================
        "Åland Islands": BigInt(220),
        "Albania": BigInt(220),
        "Andorra": BigInt(220),
        "Armenia": BigInt(220),
        "Austria": BigInt(220),
        "Azerbaijan": BigInt(220),
        "Belarus": BigInt(220),
        "Belgium": BigInt(220),
        "Bosnia and Herzegovina": BigInt(220),
        "Bulgaria": BigInt(220),
        "Croatia": BigInt(220),
        "Cyprus": BigInt(220),
        "Czechia": BigInt(220),
        "Denmark": BigInt(220),
        "Estonia": BigInt(220),
        "Faroe Islands": BigInt(220),
        "Finland": BigInt(220),
        "France": BigInt(220),
        "Georgia": BigInt(220),
        "Germany": BigInt(220),
        "Gibraltar": BigInt(220),
        "Greece": BigInt(220),
        "Greenland": BigInt(220),
        "Hungary": BigInt(220),
        "Iceland": BigInt(220),
        "Italy": BigInt(220),
        "Latvia": BigInt(220),
        "Liechtenstein": BigInt(220),
        "Lithuania": BigInt(220),
        "Luxembourg": BigInt(220),
        "North Macedonia": BigInt(220),
        "Malta": BigInt(220),
        "Moldova": BigInt(220),
        "Monaco": BigInt(220),
        "Montenegro": BigInt(220),
        "Netherlands": BigInt(220),
        "Norway": BigInt(220),
        "Poland": BigInt(220),
        "Portugal": BigInt(220),
        "Romania": BigInt(220),
        "Russia": BigInt(220),
        "San Marino": BigInt(220),
        "Serbia": BigInt(220),
        "Slovakia": BigInt(220),
        "Slovenia": BigInt(220),
        "Spain": BigInt(220),
        "Svalbard and Jan Mayen": BigInt(220),
        "Sweden": BigInt(220),
        "Switzerland": BigInt(220),
        "Turkey": BigInt(220),
        "Ukraine": BigInt(220),
        "Holy See (Vatican City)": BigInt(220),

        // ==========================================
        // REGION 3: UK & IRELAND ($230)
        // ==========================================
        "United Kingdom": BigInt(230),
        "Ireland": BigInt(230),
        "Guernsey": BigInt(230),
        "Isle of Man": BigInt(230),
        "Jersey": BigInt(230),

        // ==========================================
        // REGION 4: ASIA PACIFIC ($260)
        // ==========================================
        "Afghanistan": BigInt(260),
        "Bangladesh": BigInt(260),
        "Bhutan": BigInt(260),
        "British Indian Ocean Territory": BigInt(260),
        "Brunei Darussalam": BigInt(260),
        "Cambodia": BigInt(260),
        "Christmas Island": BigInt(260),
        "Cocos (Keeling) Islands": BigInt(260),
        "India": BigInt(260),
        "Indonesia": BigInt(260),
        "Japan": BigInt(260),
        "Kazakhstan": BigInt(260),
        "Kyrgyzstan": BigInt(260),
        "Laos": BigInt(260),
        "Malaysia": BigInt(260),
        "Maldives": BigInt(260),
        "Mongolia": BigInt(260),
        "Myanmar": BigInt(260),
        "Nepal": BigInt(260),
        "Pakistan": BigInt(260),
        "Philippines": BigInt(260),
        "Singapore": BigInt(260),
        "Sri Lanka": BigInt(260),
        "Taiwan": BigInt(260),
        "Tajikistan": BigInt(260),
        "Thailand": BigInt(260),
        "Timor-Leste": BigInt(260),
        "Turkmenistan": BigInt(260),
        "Uzbekistan": BigInt(260),
        "Vietnam": BigInt(260),

        // ==========================================
        // REGION 5: CHINA ($210)
        // ==========================================
        "China": BigInt(210),
        "Hong Kong": BigInt(210),
        "Macao": BigInt(210),

        // ==========================================
        // REGION 6: AUSTRALIA & NEW ZEALAND ($280)
        // ==========================================
        "Australia": BigInt(280),
        "New Zealand": BigInt(280),
        "American Samoa": BigInt(280),
        "Cook Islands": BigInt(280),
        "Fiji": BigInt(210), // Preserved original custom rate baseline override
        "French Polynesia": BigInt(280),
        "Guam": BigInt(280),
        "Heard Island and McDonald Islands": BigInt(280),
        "Kiribati": BigInt(280),
        "Marshall Islands": BigInt(280),
        "Micronesia": BigInt(280),
        "Nauru": BigInt(280),
        "New Caledonia": BigInt(280),
        "Niue": BigInt(280),
        "Norfolk Island": BigInt(280),
        "Northern Mariana Islands": BigInt(280),
        "Palau": BigInt(280),
        "Papua New Guinea": BigInt(280),
        "Pitcairn": BigInt(280),
        "Samoa": BigInt(210), // Preserved original custom rate baseline override
        "Solomon Islands": BigInt(280),
        "Tokelau": BigInt(280),
        "Tonga": BigInt(280),
        "Tuvalu": BigInt(280),
        "United States Minor Outlying Islands": BigInt(280),
        "Vanuatu": BigInt(280),
        "Wallis and Futuna": BigInt(280),

        // ==========================================
        // REGION 7: MIDDLE EAST ($300)
        // ==========================================
        "Bahrain": BigInt(300),
        "Iran": BigInt(300),
        "Iraq": BigInt(300),
        "Israel": BigInt(300),
        "Jordan": BigInt(300),
        "Kuwait": BigInt(300),
        "Lebanon": BigInt(300),
        "Oman": BigInt(300),
        "Palestine, State of": BigInt(300),
        "Qatar": BigInt(300),
        "Saudi Arabia": BigInt(300),
        "Syrian Arab Republic": BigInt(300),
        "United Arab Emirates": BigInt(300),
        "Yemen": BigInt(300),

        // ==========================================
        // REGION 8: AFRICA ($350)
        // ==========================================
        "Algeria": BigInt(350),
        "Angola": BigInt(350),
        "Antarctica": BigInt(350),
        "Benin": BigInt(350),
        "Botswana": BigInt(350),
        "Bouvet Island": BigInt(350),
        "Burkina Faso": BigInt(350),
        "Burundi": BigInt(350),
        "Cabo Verde": BigInt(350),
        "Cameroon": BigInt(350),
        "Central African Republic": BigInt(350),
        "Chad": BigInt(350),
        "Comoros": BigInt(350),
        "Congo, Democratic Republic of the": BigInt(350),
        "Congo, Republic of": BigInt(350),
        "Côte d'Ivoire": BigInt(350),
        "Djibouti": BigInt(350),
        "Egypt": BigInt(350),
        "Equatorial Guinea": BigInt(350),
        "Eritrea": BigInt(350),
        "Eswatini": BigInt(350),
        "Ethiopia": BigInt(350),
        "French Southern Territories": BigInt(350),
        "Gabon": BigInt(350),
        "Gambia": BigInt(350),
        "Ghana": BigInt(350),
        "Guinea": BigInt(350),
        "Guinea-Bissau": BigInt(350),
        "Kenya": BigInt(350),
        "Lesotho": BigInt(350),
        "Liberia": BigInt(350),
        "Libya": BigInt(350),
        "Madagascar": BigInt(350),
        "Malawi": BigInt(350),
        "Mali": BigInt(350),
        "Mauritania": BigInt(350),
        "Mauritius": BigInt(350),
        "Mayotte": BigInt(350),
        "Morocco": BigInt(350),
        "Mozambique": BigInt(350),
        "Namibia": BigInt(350),
        "Niger": BigInt(350),
        "Nigeria": BigInt(350),
        "Réunion": BigInt(350),
        "Rwanda": BigInt(350),
        "Saint Helena, Ascension and Tristan da Cunha": BigInt(350),
        "São Tomé and Príncipe": BigInt(350),
        "Senegal": BigInt(350),
        "Seychelles": BigInt(350),
        "Sierra Leone": BigInt(350),
        "Somalia": BigInt(350),
        "South Africa": BigInt(350),
        "South Sudan": BigInt(350),
        "Sudan": BigInt(350),
        "Tanzania": BigInt(350),
        "Togo": BigInt(350),
        "Tunisia": BigInt(350),
        "Uganda": BigInt(350),
        "Western Sahara": BigInt(350),
        "Zambia": BigInt(350),
        "Zimbabwe": BigInt(350)
      },
      baseDays: 180,
    },
    LGX300KVA: {
      assetId: 1207300,
      price: BigInt(69300),
      panel: {
        standard: { label: "480v 3-Phase @60Hz", price: BigInt(0) },
        customized: { label: "Customize", price: BigInt(1_100) },
      },
      gridTie: {
        standard: { label: "Stand Alone", price: BigInt(0) },
        Rating400: { label: "Grid Tie (400amp Rating)", price: BigInt(5_500) },
        Rating1260: { label: "Grid Tie (1260amp Rating)", price: BigInt(22_000) },
        Rating2100: { label: "Grid Tie (2100amp Rating)", price: BigInt(30_800) },
      },
      monitoring: {
        standard: { label: "No Monitoring", price: BigInt(0) },
        customized: { label: "Monitoring", price: BigInt(2_200) },
      },
      countries: {
        // ==========================================
        // REGION 0: NORTH AMERICA ($180)
        // ==========================================
        "United States of America": BigInt(180),
        "Canada": BigInt(180),
        "Mexico": BigInt(180),
        "Puerto Rico": BigInt(180),
        "Anguilla": BigInt(180),
        "Antigua and Barbuda": BigInt(180),
        "Aruba": BigInt(180),
        "Bahamas": BigInt(180),
        "Barbados": BigInt(180),
        "Belize": BigInt(180),
        "Bermuda": BigInt(180),
        "Bonaire, Sint Eustatius and Saba": BigInt(180),
        "Cayman Islands": BigInt(180),
        "Costa Rica": BigInt(180),
        "Cuba": BigInt(180),
        "Curaçao": BigInt(180),
        "Dominica": BigInt(180),
        "Dominican Republic": BigInt(180),
        "El Salvador": BigInt(180),
        "Grenada": BigInt(180),
        "Guadeloupe": BigInt(180),
        "Guatemala": BigInt(180),
        "Haiti": BigInt(180),
        "Honduras": BigInt(180),
        "Jamaica": BigInt(180),
        "Saint Kitts and Nevis": BigInt(180),
        "Saint Lucia": BigInt(180),
        "Martinique": BigInt(180),
        "Montserrat": BigInt(180),
        "Nicaragua": BigInt(180),
        "Panama": BigInt(180),
        "Saint Barthélemy": BigInt(180),
        "Saint Martin (French part)": BigInt(180),
        "Saint Pierre and Miquelon": BigInt(180),
        "Saint Vincent and the Grenadines": BigInt(180),
        "Sint Maarten (Dutch part)": BigInt(180),
        "Trinidad and Tobago": BigInt(180),
        "Turks and Caicos Islands": BigInt(180),
        "Virgin Islands (British)": BigInt(180),
        "Virgin Islands (U.S.)": BigInt(180),

        // ==========================================
        // REGION 1: SOUTH AMERICA ($250)
        // ==========================================
        "Argentina": BigInt(250),
        "Bolivia": BigInt(250),
        "Brazil": BigInt(250),
        "Chile": BigInt(250),
        "Colombia": BigInt(250),
        "Ecuador": BigInt(250),
        "Falkland Islands": BigInt(250),
        "French Guiana": BigInt(250),
        "South Georgia and the South Sandwich Islands": BigInt(250),
        "Guyana": BigInt(250),
        "Paraguay": BigInt(250),
        "Peru": BigInt(250),
        "Suriname": BigInt(250),
        "Uruguay": BigInt(250),
        "Venezuela": BigInt(250),

        // ==========================================
        // REGION 2: EUROPE ($220)
        // ==========================================
        "Åland Islands": BigInt(220),
        "Albania": BigInt(220),
        "Andorra": BigInt(220),
        "Armenia": BigInt(220),
        "Austria": BigInt(220),
        "Azerbaijan": BigInt(220),
        "Belarus": BigInt(220),
        "Belgium": BigInt(220),
        "Bosnia and Herzegovina": BigInt(220),
        "Bulgaria": BigInt(220),
        "Croatia": BigInt(220),
        "Cyprus": BigInt(220),
        "Czechia": BigInt(220),
        "Denmark": BigInt(220),
        "Estonia": BigInt(220),
        "Faroe Islands": BigInt(220),
        "Finland": BigInt(220),
        "France": BigInt(220),
        "Georgia": BigInt(220),
        "Germany": BigInt(220),
        "Gibraltar": BigInt(220),
        "Greece": BigInt(220),
        "Greenland": BigInt(220),
        "Hungary": BigInt(220),
        "Iceland": BigInt(220),
        "Italy": BigInt(220),
        "Latvia": BigInt(220),
        "Liechtenstein": BigInt(220),
        "Lithuania": BigInt(220),
        "Luxembourg": BigInt(220),
        "North Macedonia": BigInt(220),
        "Malta": BigInt(220),
        "Moldova": BigInt(220),
        "Monaco": BigInt(220),
        "Montenegro": BigInt(220),
        "Netherlands": BigInt(220),
        "Norway": BigInt(220),
        "Poland": BigInt(220),
        "Portugal": BigInt(220),
        "Romania": BigInt(220),
        "Russia": BigInt(220),
        "San Marino": BigInt(220),
        "Serbia": BigInt(220),
        "Slovakia": BigInt(220),
        "Slovenia": BigInt(220),
        "Spain": BigInt(220),
        "Svalbard and Jan Mayen": BigInt(220),
        "Sweden": BigInt(220),
        "Switzerland": BigInt(220),
        "Turkey": BigInt(220),
        "Ukraine": BigInt(220),
        "Holy See (Vatican City)": BigInt(220),

        // ==========================================
        // REGION 3: UK & IRELAND ($230)
        // ==========================================
        "United Kingdom": BigInt(230),
        "Ireland": BigInt(230),
        "Guernsey": BigInt(230),
        "Isle of Man": BigInt(230),
        "Jersey": BigInt(230),

        // ==========================================
        // REGION 4: ASIA PACIFIC ($260)
        // ==========================================
        "Afghanistan": BigInt(260),
        "Bangladesh": BigInt(260),
        "Bhutan": BigInt(260),
        "British Indian Ocean Territory": BigInt(260),
        "Brunei Darussalam": BigInt(260),
        "Cambodia": BigInt(260),
        "Christmas Island": BigInt(260),
        "Cocos (Keeling) Islands": BigInt(260),
        "India": BigInt(260),
        "Indonesia": BigInt(260),
        "Japan": BigInt(260),
        "Kazakhstan": BigInt(260),
        "Kyrgyzstan": BigInt(260),
        "Laos": BigInt(260),
        "Malaysia": BigInt(260),
        "Maldives": BigInt(260),
        "Mongolia": BigInt(260),
        "Myanmar": BigInt(260),
        "Nepal": BigInt(260),
        "Pakistan": BigInt(260),
        "Philippines": BigInt(260),
        "Singapore": BigInt(260),
        "Sri Lanka": BigInt(260),
        "Taiwan": BigInt(260),
        "Tajikistan": BigInt(260),
        "Thailand": BigInt(260),
        "Timor-Leste": BigInt(260),
        "Turkmenistan": BigInt(260),
        "Uzbekistan": BigInt(260),
        "Vietnam": BigInt(260),

        // ==========================================
        // REGION 5: CHINA ($210)
        // ==========================================
        "China": BigInt(210),
        "Hong Kong": BigInt(210),
        "Macao": BigInt(210),

        // ==========================================
        // REGION 6: AUSTRALIA & NEW ZEALAND ($280)
        // ==========================================
        "Australia": BigInt(280),
        "New Zealand": BigInt(280),
        "American Samoa": BigInt(280),
        "Cook Islands": BigInt(280),
        "Fiji": BigInt(210), // Preserved original custom rate baseline override
        "French Polynesia": BigInt(280),
        "Guam": BigInt(280),
        "Heard Island and McDonald Islands": BigInt(280),
        "Kiribati": BigInt(280),
        "Marshall Islands": BigInt(280),
        "Micronesia": BigInt(280),
        "Nauru": BigInt(280),
        "New Caledonia": BigInt(280),
        "Niue": BigInt(280),
        "Norfolk Island": BigInt(280),
        "Northern Mariana Islands": BigInt(280),
        "Palau": BigInt(280),
        "Papua New Guinea": BigInt(280),
        "Pitcairn": BigInt(280),
        "Samoa": BigInt(210), // Preserved original custom rate baseline override
        "Solomon Islands": BigInt(280),
        "Tokelau": BigInt(280),
        "Tonga": BigInt(280),
        "Tuvalu": BigInt(280),
        "United States Minor Outlying Islands": BigInt(280),
        "Vanuatu": BigInt(280),
        "Wallis and Futuna": BigInt(280),

        // ==========================================
        // REGION 7: MIDDLE EAST ($300)
        // ==========================================
        "Bahrain": BigInt(300),
        "Iran": BigInt(300),
        "Iraq": BigInt(300),
        "Israel": BigInt(300),
        "Jordan": BigInt(300),
        "Kuwait": BigInt(300),
        "Lebanon": BigInt(300),
        "Oman": BigInt(300),
        "Palestine, State of": BigInt(300),
        "Qatar": BigInt(300),
        "Saudi Arabia": BigInt(300),
        "Syrian Arab Republic": BigInt(300),
        "United Arab Emirates": BigInt(300),
        "Yemen": BigInt(300),

        // ==========================================
        // REGION 8: AFRICA ($350)
        // ==========================================
        "Algeria": BigInt(350),
        "Angola": BigInt(350),
        "Antarctica": BigInt(350),
        "Benin": BigInt(350),
        "Botswana": BigInt(350),
        "Bouvet Island": BigInt(350),
        "Burkina Faso": BigInt(350),
        "Burundi": BigInt(350),
        "Cabo Verde": BigInt(350),
        "Cameroon": BigInt(350),
        "Central African Republic": BigInt(350),
        "Chad": BigInt(350),
        "Comoros": BigInt(350),
        "Congo, Democratic Republic of the": BigInt(350),
        "Congo, Republic of": BigInt(350),
        "Côte d'Ivoire": BigInt(350),
        "Djibouti": BigInt(350),
        "Egypt": BigInt(350),
        "Equatorial Guinea": BigInt(350),
        "Eritrea": BigInt(350),
        "Eswatini": BigInt(350),
        "Ethiopia": BigInt(350),
        "French Southern Territories": BigInt(350),
        "Gabon": BigInt(350),
        "Gambia": BigInt(350),
        "Ghana": BigInt(350),
        "Guinea": BigInt(350),
        "Guinea-Bissau": BigInt(350),
        "Kenya": BigInt(350),
        "Lesotho": BigInt(350),
        "Liberia": BigInt(350),
        "Libya": BigInt(350),
        "Madagascar": BigInt(350),
        "Malawi": BigInt(350),
        "Mali": BigInt(350),
        "Mauritania": BigInt(350),
        "Mauritius": BigInt(350),
        "Mayotte": BigInt(350),
        "Morocco": BigInt(350),
        "Mozambique": BigInt(350),
        "Namibia": BigInt(350),
        "Niger": BigInt(350),
        "Nigeria": BigInt(350),
        "Réunion": BigInt(350),
        "Rwanda": BigInt(350),
        "Saint Helena, Ascension and Tristan da Cunha": BigInt(350),
        "São Tomé and Príncipe": BigInt(350),
        "Senegal": BigInt(350),
        "Seychelles": BigInt(350),
        "Sierra Leone": BigInt(350),
        "Somalia": BigInt(350),
        "South Africa": BigInt(350),
        "South Sudan": BigInt(350),
        "Sudan": BigInt(350),
        "Tanzania": BigInt(350),
        "Togo": BigInt(350),
        "Tunisia": BigInt(350),
        "Uganda": BigInt(350),
        "Western Sahara": BigInt(350),
        "Zambia": BigInt(350),
        "Zimbabwe": BigInt(350)
      },
      baseDays: 180,
    },
    LGX400KVA: {
      assetId: 1207400,
      price: BigInt(80300),
      panel: {
        standard: { label: "480v 3-Phase @60Hz", price: BigInt(0) },
        customized: { label: "Customize", price: BigInt(1_100) },
      },
      gridTie: {
        standard: { label: "Stand Alone", price: BigInt(0) },
        Rating400: { label: "Grid Tie (400amp Rating)", price: BigInt(5_500) },
        Rating1260: { label: "Grid Tie (1260amp Rating)", price: BigInt(22_0000) },
        Rating2100: { label: "Grid Tie (2100amp Rating)", price: BigInt(30_800) },
      },
      monitoring: {
        standard: { label: "No Monitoring", price: BigInt(0) },
        customized: { label: "Monitoring", price: BigInt(2_200) },
      },
      countries: {
        // ==========================================
        // REGION 0: NORTH AMERICA ($180)
        // ==========================================
        "United States of America": BigInt(180),
        "Canada": BigInt(180),
        "Mexico": BigInt(180),
        "Puerto Rico": BigInt(180),
        "Anguilla": BigInt(180),
        "Antigua and Barbuda": BigInt(180),
        "Aruba": BigInt(180),
        "Bahamas": BigInt(180),
        "Barbados": BigInt(180),
        "Belize": BigInt(180),
        "Bermuda": BigInt(180),
        "Bonaire, Sint Eustatius and Saba": BigInt(180),
        "Cayman Islands": BigInt(180),
        "Costa Rica": BigInt(180),
        "Cuba": BigInt(180),
        "Curaçao": BigInt(180),
        "Dominica": BigInt(180),
        "Dominican Republic": BigInt(180),
        "El Salvador": BigInt(180),
        "Grenada": BigInt(180),
        "Guadeloupe": BigInt(180),
        "Guatemala": BigInt(180),
        "Haiti": BigInt(180),
        "Honduras": BigInt(180),
        "Jamaica": BigInt(180),
        "Saint Kitts and Nevis": BigInt(180),
        "Saint Lucia": BigInt(180),
        "Martinique": BigInt(180),
        "Montserrat": BigInt(180),
        "Nicaragua": BigInt(180),
        "Panama": BigInt(180),
        "Saint Barthélemy": BigInt(180),
        "Saint Martin (French part)": BigInt(180),
        "Saint Pierre and Miquelon": BigInt(180),
        "Saint Vincent and the Grenadines": BigInt(180),
        "Sint Maarten (Dutch part)": BigInt(180),
        "Trinidad and Tobago": BigInt(180),
        "Turks and Caicos Islands": BigInt(180),
        "Virgin Islands (British)": BigInt(180),
        "Virgin Islands (U.S.)": BigInt(180),

        // ==========================================
        // REGION 1: SOUTH AMERICA ($250)
        // ==========================================
        "Argentina": BigInt(250),
        "Bolivia": BigInt(250),
        "Brazil": BigInt(250),
        "Chile": BigInt(250),
        "Colombia": BigInt(250),
        "Ecuador": BigInt(250),
        "Falkland Islands": BigInt(250),
        "French Guiana": BigInt(250),
        "South Georgia and the South Sandwich Islands": BigInt(250),
        "Guyana": BigInt(250),
        "Paraguay": BigInt(250),
        "Peru": BigInt(250),
        "Suriname": BigInt(250),
        "Uruguay": BigInt(250),
        "Venezuela": BigInt(250),

        // ==========================================
        // REGION 2: EUROPE ($220)
        // ==========================================
        "Åland Islands": BigInt(220),
        "Albania": BigInt(220),
        "Andorra": BigInt(220),
        "Armenia": BigInt(220),
        "Austria": BigInt(220),
        "Azerbaijan": BigInt(220),
        "Belarus": BigInt(220),
        "Belgium": BigInt(220),
        "Bosnia and Herzegovina": BigInt(220),
        "Bulgaria": BigInt(220),
        "Croatia": BigInt(220),
        "Cyprus": BigInt(220),
        "Czechia": BigInt(220),
        "Denmark": BigInt(220),
        "Estonia": BigInt(220),
        "Faroe Islands": BigInt(220),
        "Finland": BigInt(220),
        "France": BigInt(220),
        "Georgia": BigInt(220),
        "Germany": BigInt(220),
        "Gibraltar": BigInt(220),
        "Greece": BigInt(220),
        "Greenland": BigInt(220),
        "Hungary": BigInt(220),
        "Iceland": BigInt(220),
        "Italy": BigInt(220),
        "Latvia": BigInt(220),
        "Liechtenstein": BigInt(220),
        "Lithuania": BigInt(220),
        "Luxembourg": BigInt(220),
        "North Macedonia": BigInt(220),
        "Malta": BigInt(220),
        "Moldova": BigInt(220),
        "Monaco": BigInt(220),
        "Montenegro": BigInt(220),
        "Netherlands": BigInt(220),
        "Norway": BigInt(220),
        "Poland": BigInt(220),
        "Portugal": BigInt(220),
        "Romania": BigInt(220),
        "Russia": BigInt(220),
        "San Marino": BigInt(220),
        "Serbia": BigInt(220),
        "Slovakia": BigInt(220),
        "Slovenia": BigInt(220),
        "Spain": BigInt(220),
        "Svalbard and Jan Mayen": BigInt(220),
        "Sweden": BigInt(220),
        "Switzerland": BigInt(220),
        "Turkey": BigInt(220),
        "Ukraine": BigInt(220),
        "Holy See (Vatican City)": BigInt(220),

        // ==========================================
        // REGION 3: UK & IRELAND ($230)
        // ==========================================
        "United Kingdom": BigInt(230),
        "Ireland": BigInt(230),
        "Guernsey": BigInt(230),
        "Isle of Man": BigInt(230),
        "Jersey": BigInt(230),

        // ==========================================
        // REGION 4: ASIA PACIFIC ($260)
        // ==========================================
        "Afghanistan": BigInt(260),
        "Bangladesh": BigInt(260),
        "Bhutan": BigInt(260),
        "British Indian Ocean Territory": BigInt(260),
        "Brunei Darussalam": BigInt(260),
        "Cambodia": BigInt(260),
        "Christmas Island": BigInt(260),
        "Cocos (Keeling) Islands": BigInt(260),
        "India": BigInt(260),
        "Indonesia": BigInt(260),
        "Japan": BigInt(260),
        "Kazakhstan": BigInt(260),
        "Kyrgyzstan": BigInt(260),
        "Laos": BigInt(260),
        "Malaysia": BigInt(260),
        "Maldives": BigInt(260),
        "Mongolia": BigInt(260),
        "Myanmar": BigInt(260),
        "Nepal": BigInt(260),
        "Pakistan": BigInt(260),
        "Philippines": BigInt(260),
        "Singapore": BigInt(260),
        "Sri Lanka": BigInt(260),
        "Taiwan": BigInt(260),
        "Tajikistan": BigInt(260),
        "Thailand": BigInt(260),
        "Timor-Leste": BigInt(260),
        "Turkmenistan": BigInt(260),
        "Uzbekistan": BigInt(260),
        "Vietnam": BigInt(260),

        // ==========================================
        // REGION 5: CHINA ($210)
        // ==========================================
        "China": BigInt(210),
        "Hong Kong": BigInt(210),
        "Macao": BigInt(210),

        // ==========================================
        // REGION 6: AUSTRALIA & NEW ZEALAND ($280)
        // ==========================================
        "Australia": BigInt(280),
        "New Zealand": BigInt(280),
        "American Samoa": BigInt(280),
        "Cook Islands": BigInt(280),
        "Fiji": BigInt(210), // Preserved original custom rate baseline override
        "French Polynesia": BigInt(280),
        "Guam": BigInt(280),
        "Heard Island and McDonald Islands": BigInt(280),
        "Kiribati": BigInt(280),
        "Marshall Islands": BigInt(280),
        "Micronesia": BigInt(280),
        "Nauru": BigInt(280),
        "New Caledonia": BigInt(280),
        "Niue": BigInt(280),
        "Norfolk Island": BigInt(280),
        "Northern Mariana Islands": BigInt(280),
        "Palau": BigInt(280),
        "Papua New Guinea": BigInt(280),
        "Pitcairn": BigInt(280),
        "Samoa": BigInt(210), // Preserved original custom rate baseline override
        "Solomon Islands": BigInt(280),
        "Tokelau": BigInt(280),
        "Tonga": BigInt(280),
        "Tuvalu": BigInt(280),
        "United States Minor Outlying Islands": BigInt(280),
        "Vanuatu": BigInt(280),
        "Wallis and Futuna": BigInt(280),

        // ==========================================
        // REGION 7: MIDDLE EAST ($300)
        // ==========================================
        "Bahrain": BigInt(300),
        "Iran": BigInt(300),
        "Iraq": BigInt(300),
        "Israel": BigInt(300),
        "Jordan": BigInt(300),
        "Kuwait": BigInt(300),
        "Lebanon": BigInt(300),
        "Oman": BigInt(300),
        "Palestine, State of": BigInt(300),
        "Qatar": BigInt(300),
        "Saudi Arabia": BigInt(300),
        "Syrian Arab Republic": BigInt(300),
        "United Arab Emirates": BigInt(300),
        "Yemen": BigInt(300),

        // ==========================================
        // REGION 8: AFRICA ($350)
        // ==========================================
        "Algeria": BigInt(350),
        "Angola": BigInt(350),
        "Antarctica": BigInt(350),
        "Benin": BigInt(350),
        "Botswana": BigInt(350),
        "Bouvet Island": BigInt(350),
        "Burkina Faso": BigInt(350),
        "Burundi": BigInt(350),
        "Cabo Verde": BigInt(350),
        "Cameroon": BigInt(350),
        "Central African Republic": BigInt(350),
        "Chad": BigInt(350),
        "Comoros": BigInt(350),
        "Congo, Democratic Republic of the": BigInt(350),
        "Congo, Republic of": BigInt(350),
        "Côte d'Ivoire": BigInt(350),
        "Djibouti": BigInt(350),
        "Egypt": BigInt(350),
        "Equatorial Guinea": BigInt(350),
        "Eritrea": BigInt(350),
        "Eswatini": BigInt(350),
        "Ethiopia": BigInt(350),
        "French Southern Territories": BigInt(350),
        "Gabon": BigInt(350),
        "Gambia": BigInt(350),
        "Ghana": BigInt(350),
        "Guinea": BigInt(350),
        "Guinea-Bissau": BigInt(350),
        "Kenya": BigInt(350),
        "Lesotho": BigInt(350),
        "Liberia": BigInt(350),
        "Libya": BigInt(350),
        "Madagascar": BigInt(350),
        "Malawi": BigInt(350),
        "Mali": BigInt(350),
        "Mauritania": BigInt(350),
        "Mauritius": BigInt(350),
        "Mayotte": BigInt(350),
        "Morocco": BigInt(350),
        "Mozambique": BigInt(350),
        "Namibia": BigInt(350),
        "Niger": BigInt(350),
        "Nigeria": BigInt(350),
        "Réunion": BigInt(350),
        "Rwanda": BigInt(350),
        "Saint Helena, Ascension and Tristan da Cunha": BigInt(350),
        "São Tomé and Príncipe": BigInt(350),
        "Senegal": BigInt(350),
        "Seychelles": BigInt(350),
        "Sierra Leone": BigInt(350),
        "Somalia": BigInt(350),
        "South Africa": BigInt(350),
        "South Sudan": BigInt(350),
        "Sudan": BigInt(350),
        "Tanzania": BigInt(350),
        "Togo": BigInt(350),
        "Tunisia": BigInt(350),
        "Uganda": BigInt(350),
        "Western Sahara": BigInt(350),
        "Zambia": BigInt(350),
        "Zimbabwe": BigInt(350)
      },
      baseDays: 180,
    },
    LGX500KVA: {
      assetId: 1207500,
      price: BigInt(88000),
      panel: {
        standard: { label: "480v 3-Phase @60Hz", price: BigInt(0) },
        customized: { label: "Customize", price: BigInt(1_100) },
      },
      gridTie: {
        standard: { label: "Stand Alone", price: BigInt(0) },
        Rating400: { label: "Grid Tie (400amp Rating)", price: BigInt(5_500) },
        Rating1260: { label: "Grid Tie (1260amp Rating)", price: BigInt(22_000) },
        Rating2100: { label: "Grid Tie (2100amp Rating)", price: BigInt(30_800) },
      },
      monitoring: {
        standard: { label: "No Monitoring", price: BigInt(0) },
        customized: { label: "Monitoring", price: BigInt(2_200) },
      },
      countries: {
        // ==========================================
        // REGION 0: NORTH AMERICA ($180)
        // ==========================================
        "United States of America": BigInt(180),
        "Canada": BigInt(180),
        "Mexico": BigInt(180),
        "Puerto Rico": BigInt(180),
        "Anguilla": BigInt(180),
        "Antigua and Barbuda": BigInt(180),
        "Aruba": BigInt(180),
        "Bahamas": BigInt(180),
        "Barbados": BigInt(180),
        "Belize": BigInt(180),
        "Bermuda": BigInt(180),
        "Bonaire, Sint Eustatius and Saba": BigInt(180),
        "Cayman Islands": BigInt(180),
        "Costa Rica": BigInt(180),
        "Cuba": BigInt(180),
        "Curaçao": BigInt(180),
        "Dominica": BigInt(180),
        "Dominican Republic": BigInt(180),
        "El Salvador": BigInt(180),
        "Grenada": BigInt(180),
        "Guadeloupe": BigInt(180),
        "Guatemala": BigInt(180),
        "Haiti": BigInt(180),
        "Honduras": BigInt(180),
        "Jamaica": BigInt(180),
        "Saint Kitts and Nevis": BigInt(180),
        "Saint Lucia": BigInt(180),
        "Martinique": BigInt(180),
        "Montserrat": BigInt(180),
        "Nicaragua": BigInt(180),
        "Panama": BigInt(180),
        "Saint Barthélemy": BigInt(180),
        "Saint Martin (French part)": BigInt(180),
        "Saint Pierre and Miquelon": BigInt(180),
        "Saint Vincent and the Grenadines": BigInt(180),
        "Sint Maarten (Dutch part)": BigInt(180),
        "Trinidad and Tobago": BigInt(180),
        "Turks and Caicos Islands": BigInt(180),
        "Virgin Islands (British)": BigInt(180),
        "Virgin Islands (U.S.)": BigInt(180),

        // ==========================================
        // REGION 1: SOUTH AMERICA ($250)
        // ==========================================
        "Argentina": BigInt(250),
        "Bolivia": BigInt(250),
        "Brazil": BigInt(250),
        "Chile": BigInt(250),
        "Colombia": BigInt(250),
        "Ecuador": BigInt(250),
        "Falkland Islands": BigInt(250),
        "French Guiana": BigInt(250),
        "South Georgia and the South Sandwich Islands": BigInt(250),
        "Guyana": BigInt(250),
        "Paraguay": BigInt(250),
        "Peru": BigInt(250),
        "Suriname": BigInt(250),
        "Uruguay": BigInt(250),
        "Venezuela": BigInt(250),

        // ==========================================
        // REGION 2: EUROPE ($220)
        // ==========================================
        "Åland Islands": BigInt(220),
        "Albania": BigInt(220),
        "Andorra": BigInt(220),
        "Armenia": BigInt(220),
        "Austria": BigInt(220),
        "Azerbaijan": BigInt(220),
        "Belarus": BigInt(220),
        "Belgium": BigInt(220),
        "Bosnia and Herzegovina": BigInt(220),
        "Bulgaria": BigInt(220),
        "Croatia": BigInt(220),
        "Cyprus": BigInt(220),
        "Czechia": BigInt(220),
        "Denmark": BigInt(220),
        "Estonia": BigInt(220),
        "Faroe Islands": BigInt(220),
        "Finland": BigInt(220),
        "France": BigInt(220),
        "Georgia": BigInt(220),
        "Germany": BigInt(220),
        "Gibraltar": BigInt(220),
        "Greece": BigInt(220),
        "Greenland": BigInt(220),
        "Hungary": BigInt(220),
        "Iceland": BigInt(220),
        "Italy": BigInt(220),
        "Latvia": BigInt(220),
        "Liechtenstein": BigInt(220),
        "Lithuania": BigInt(220),
        "Luxembourg": BigInt(220),
        "North Macedonia": BigInt(220),
        "Malta": BigInt(220),
        "Moldova": BigInt(220),
        "Monaco": BigInt(220),
        "Montenegro": BigInt(220),
        "Netherlands": BigInt(220),
        "Norway": BigInt(220),
        "Poland": BigInt(220),
        "Portugal": BigInt(220),
        "Romania": BigInt(220),
        "Russia": BigInt(220),
        "San Marino": BigInt(220),
        "Serbia": BigInt(220),
        "Slovakia": BigInt(220),
        "Slovenia": BigInt(220),
        "Spain": BigInt(220),
        "Svalbard and Jan Mayen": BigInt(220),
        "Sweden": BigInt(220),
        "Switzerland": BigInt(220),
        "Turkey": BigInt(220),
        "Ukraine": BigInt(220),
        "Holy See (Vatican City)": BigInt(220),

        // ==========================================
        // REGION 3: UK & IRELAND ($230)
        // ==========================================
        "United Kingdom": BigInt(230),
        "Ireland": BigInt(230),
        "Guernsey": BigInt(230),
        "Isle of Man": BigInt(230),
        "Jersey": BigInt(230),

        // ==========================================
        // REGION 4: ASIA PACIFIC ($260)
        // ==========================================
        "Afghanistan": BigInt(260),
        "Bangladesh": BigInt(260),
        "Bhutan": BigInt(260),
        "British Indian Ocean Territory": BigInt(260),
        "Brunei Darussalam": BigInt(260),
        "Cambodia": BigInt(260),
        "Christmas Island": BigInt(260),
        "Cocos (Keeling) Islands": BigInt(260),
        "India": BigInt(260),
        "Indonesia": BigInt(260),
        "Japan": BigInt(260),
        "Kazakhstan": BigInt(260),
        "Kyrgyzstan": BigInt(260),
        "Laos": BigInt(260),
        "Malaysia": BigInt(260),
        "Maldives": BigInt(260),
        "Mongolia": BigInt(260),
        "Myanmar": BigInt(260),
        "Nepal": BigInt(260),
        "Pakistan": BigInt(260),
        "Philippines": BigInt(260),
        "Singapore": BigInt(260),
        "Sri Lanka": BigInt(260),
        "Taiwan": BigInt(260),
        "Tajikistan": BigInt(260),
        "Thailand": BigInt(260),
        "Timor-Leste": BigInt(260),
        "Turkmenistan": BigInt(260),
        "Uzbekistan": BigInt(260),
        "Vietnam": BigInt(260),

        // ==========================================
        // REGION 5: CHINA ($210)
        // ==========================================
        "China": BigInt(210),
        "Hong Kong": BigInt(210),
        "Macao": BigInt(210),

        // ==========================================
        // REGION 6: AUSTRALIA & NEW ZEALAND ($280)
        // ==========================================
        "Australia": BigInt(280),
        "New Zealand": BigInt(280),
        "American Samoa": BigInt(280),
        "Cook Islands": BigInt(280),
        "Fiji": BigInt(210), // Preserved original custom rate baseline override
        "French Polynesia": BigInt(280),
        "Guam": BigInt(280),
        "Heard Island and McDonald Islands": BigInt(280),
        "Kiribati": BigInt(280),
        "Marshall Islands": BigInt(280),
        "Micronesia": BigInt(280),
        "Nauru": BigInt(280),
        "New Caledonia": BigInt(280),
        "Niue": BigInt(280),
        "Norfolk Island": BigInt(280),
        "Northern Mariana Islands": BigInt(280),
        "Palau": BigInt(280),
        "Papua New Guinea": BigInt(280),
        "Pitcairn": BigInt(280),
        "Samoa": BigInt(210), // Preserved original custom rate baseline override
        "Solomon Islands": BigInt(280),
        "Tokelau": BigInt(280),
        "Tonga": BigInt(280),
        "Tuvalu": BigInt(280),
        "United States Minor Outlying Islands": BigInt(280),
        "Vanuatu": BigInt(280),
        "Wallis and Futuna": BigInt(280),

        // ==========================================
        // REGION 7: MIDDLE EAST ($300)
        // ==========================================
        "Bahrain": BigInt(300),
        "Iran": BigInt(300),
        "Iraq": BigInt(300),
        "Israel": BigInt(300),
        "Jordan": BigInt(300),
        "Kuwait": BigInt(300),
        "Lebanon": BigInt(300),
        "Oman": BigInt(300),
        "Palestine, State of": BigInt(300),
        "Qatar": BigInt(300),
        "Saudi Arabia": BigInt(300),
        "Syrian Arab Republic": BigInt(300),
        "United Arab Emirates": BigInt(300),
        "Yemen": BigInt(300),

        // ==========================================
        // REGION 8: AFRICA ($350)
        // ==========================================
        "Algeria": BigInt(350),
        "Angola": BigInt(350),
        "Antarctica": BigInt(350),
        "Benin": BigInt(350),
        "Botswana": BigInt(350),
        "Bouvet Island": BigInt(350),
        "Burkina Faso": BigInt(350),
        "Burundi": BigInt(350),
        "Cabo Verde": BigInt(350),
        "Cameroon": BigInt(350),
        "Central African Republic": BigInt(350),
        "Chad": BigInt(350),
        "Comoros": BigInt(350),
        "Congo, Democratic Republic of the": BigInt(350),
        "Congo, Republic of": BigInt(350),
        "Côte d'Ivoire": BigInt(350),
        "Djibouti": BigInt(350),
        "Egypt": BigInt(350),
        "Equatorial Guinea": BigInt(350),
        "Eritrea": BigInt(350),
        "Eswatini": BigInt(350),
        "Ethiopia": BigInt(350),
        "French Southern Territories": BigInt(350),
        "Gabon": BigInt(350),
        "Gambia": BigInt(350),
        "Ghana": BigInt(350),
        "Guinea": BigInt(350),
        "Guinea-Bissau": BigInt(350),
        "Kenya": BigInt(350),
        "Lesotho": BigInt(350),
        "Liberia": BigInt(350),
        "Libya": BigInt(350),
        "Madagascar": BigInt(350),
        "Malawi": BigInt(350),
        "Mali": BigInt(350),
        "Mauritania": BigInt(350),
        "Mauritius": BigInt(350),
        "Mayotte": BigInt(350),
        "Morocco": BigInt(350),
        "Mozambique": BigInt(350),
        "Namibia": BigInt(350),
        "Niger": BigInt(350),
        "Nigeria": BigInt(350),
        "Réunion": BigInt(350),
        "Rwanda": BigInt(350),
        "Saint Helena, Ascension and Tristan da Cunha": BigInt(350),
        "São Tomé and Príncipe": BigInt(350),
        "Senegal": BigInt(350),
        "Seychelles": BigInt(350),
        "Sierra Leone": BigInt(350),
        "Somalia": BigInt(350),
        "South Africa": BigInt(350),
        "South Sudan": BigInt(350),
        "Sudan": BigInt(350),
        "Tanzania": BigInt(350),
        "Togo": BigInt(350),
        "Tunisia": BigInt(350),
        "Uganda": BigInt(350),
        "Western Sahara": BigInt(350),
        "Zambia": BigInt(350),
        "Zimbabwe": BigInt(350)
      },
      baseDays: 180,
    },
    LGX60OKVA: {
      assetId: 1207600,
      price: BigInt(99000),
      panel: {
        standard: { label: "480v 3-Phase @60Hz", price: BigInt(0) },
        customized: { label: "Customize", price: BigInt(1_100) },
      },
      gridTie: {
        standard: { label: "Stand Alone", price: BigInt(0) },
        Rating400: { label: "Grid Tie (400amp Rating)", price: BigInt(5_500) },
        Rating1260: { label: "Grid Tie (1260amp Rating)", price: BigInt(22_000) },
        Rating2100: { label: "Grid Tie (2100amp Rating)", price: BigInt(30_800) },
      },
      monitoring: {
        standard: { label: "No Monitoring", price: BigInt(0) },
        customized: { label: "Monitoring", price: BigInt(2_200) },
      },
      countries: {
        // ==========================================
        // REGION 0: NORTH AMERICA ($180)
        // ==========================================
        "United States of America": BigInt(180),
        "Canada": BigInt(180),
        "Mexico": BigInt(180),
        "Puerto Rico": BigInt(180),
        "Anguilla": BigInt(180),
        "Antigua and Barbuda": BigInt(180),
        "Aruba": BigInt(180),
        "Bahamas": BigInt(180),
        "Barbados": BigInt(180),
        "Belize": BigInt(180),
        "Bermuda": BigInt(180),
        "Bonaire, Sint Eustatius and Saba": BigInt(180),
        "Cayman Islands": BigInt(180),
        "Costa Rica": BigInt(180),
        "Cuba": BigInt(180),
        "Curaçao": BigInt(180),
        "Dominica": BigInt(180),
        "Dominican Republic": BigInt(180),
        "El Salvador": BigInt(180),
        "Grenada": BigInt(180),
        "Guadeloupe": BigInt(180),
        "Guatemala": BigInt(180),
        "Haiti": BigInt(180),
        "Honduras": BigInt(180),
        "Jamaica": BigInt(180),
        "Saint Kitts and Nevis": BigInt(180),
        "Saint Lucia": BigInt(180),
        "Martinique": BigInt(180),
        "Montserrat": BigInt(180),
        "Nicaragua": BigInt(180),
        "Panama": BigInt(180),
        "Saint Barthélemy": BigInt(180),
        "Saint Martin (French part)": BigInt(180),
        "Saint Pierre and Miquelon": BigInt(180),
        "Saint Vincent and the Grenadines": BigInt(180),
        "Sint Maarten (Dutch part)": BigInt(180),
        "Trinidad and Tobago": BigInt(180),
        "Turks and Caicos Islands": BigInt(180),
        "Virgin Islands (British)": BigInt(180),
        "Virgin Islands (U.S.)": BigInt(180),

        // ==========================================
        // REGION 1: SOUTH AMERICA ($250)
        // ==========================================
        "Argentina": BigInt(250),
        "Bolivia": BigInt(250),
        "Brazil": BigInt(250),
        "Chile": BigInt(250),
        "Colombia": BigInt(250),
        "Ecuador": BigInt(250),
        "Falkland Islands": BigInt(250),
        "French Guiana": BigInt(250),
        "South Georgia and the South Sandwich Islands": BigInt(250),
        "Guyana": BigInt(250),
        "Paraguay": BigInt(250),
        "Peru": BigInt(250),
        "Suriname": BigInt(250),
        "Uruguay": BigInt(250),
        "Venezuela": BigInt(250),

        // ==========================================
        // REGION 2: EUROPE ($220)
        // ==========================================
        "Åland Islands": BigInt(220),
        "Albania": BigInt(220),
        "Andorra": BigInt(220),
        "Armenia": BigInt(220),
        "Austria": BigInt(220),
        "Azerbaijan": BigInt(220),
        "Belarus": BigInt(220),
        "Belgium": BigInt(220),
        "Bosnia and Herzegovina": BigInt(220),
        "Bulgaria": BigInt(220),
        "Croatia": BigInt(220),
        "Cyprus": BigInt(220),
        "Czechia": BigInt(220),
        "Denmark": BigInt(220),
        "Estonia": BigInt(220),
        "Faroe Islands": BigInt(220),
        "Finland": BigInt(220),
        "France": BigInt(220),
        "Georgia": BigInt(220),
        "Germany": BigInt(220),
        "Gibraltar": BigInt(220),
        "Greece": BigInt(220),
        "Greenland": BigInt(220),
        "Hungary": BigInt(220),
        "Iceland": BigInt(220),
        "Italy": BigInt(220),
        "Latvia": BigInt(220),
        "Liechtenstein": BigInt(220),
        "Lithuania": BigInt(220),
        "Luxembourg": BigInt(220),
        "North Macedonia": BigInt(220),
        "Malta": BigInt(220),
        "Moldova": BigInt(220),
        "Monaco": BigInt(220),
        "Montenegro": BigInt(220),
        "Netherlands": BigInt(220),
        "Norway": BigInt(220),
        "Poland": BigInt(220),
        "Portugal": BigInt(220),
        "Romania": BigInt(220),
        "Russia": BigInt(220),
        "San Marino": BigInt(220),
        "Serbia": BigInt(220),
        "Slovakia": BigInt(220),
        "Slovenia": BigInt(220),
        "Spain": BigInt(220),
        "Svalbard and Jan Mayen": BigInt(220),
        "Sweden": BigInt(220),
        "Switzerland": BigInt(220),
        "Turkey": BigInt(220),
        "Ukraine": BigInt(220),
        "Holy See (Vatican City)": BigInt(220),

        // ==========================================
        // REGION 3: UK & IRELAND ($230)
        // ==========================================
        "United Kingdom": BigInt(230),
        "Ireland": BigInt(230),
        "Guernsey": BigInt(230),
        "Isle of Man": BigInt(230),
        "Jersey": BigInt(230),

        // ==========================================
        // REGION 4: ASIA PACIFIC ($260)
        // ==========================================
        "Afghanistan": BigInt(260),
        "Bangladesh": BigInt(260),
        "Bhutan": BigInt(260),
        "British Indian Ocean Territory": BigInt(260),
        "Brunei Darussalam": BigInt(260),
        "Cambodia": BigInt(260),
        "Christmas Island": BigInt(260),
        "Cocos (Keeling) Islands": BigInt(260),
        "India": BigInt(260),
        "Indonesia": BigInt(260),
        "Japan": BigInt(260),
        "Kazakhstan": BigInt(260),
        "Kyrgyzstan": BigInt(260),
        "Laos": BigInt(260),
        "Malaysia": BigInt(260),
        "Maldives": BigInt(260),
        "Mongolia": BigInt(260),
        "Myanmar": BigInt(260),
        "Nepal": BigInt(260),
        "Pakistan": BigInt(260),
        "Philippines": BigInt(260),
        "Singapore": BigInt(260),
        "Sri Lanka": BigInt(260),
        "Taiwan": BigInt(260),
        "Tajikistan": BigInt(260),
        "Thailand": BigInt(260),
        "Timor-Leste": BigInt(260),
        "Turkmenistan": BigInt(260),
        "Uzbekistan": BigInt(260),
        "Vietnam": BigInt(260),

        // ==========================================
        // REGION 5: CHINA ($210)
        // ==========================================
        "China": BigInt(210),
        "Hong Kong": BigInt(210),
        "Macao": BigInt(210),

        // ==========================================
        // REGION 6: AUSTRALIA & NEW ZEALAND ($280)
        // ==========================================
        "Australia": BigInt(280),
        "New Zealand": BigInt(280),
        "American Samoa": BigInt(280),
        "Cook Islands": BigInt(280),
        "Fiji": BigInt(210), // Preserved original custom rate baseline override
        "French Polynesia": BigInt(280),
        "Guam": BigInt(280),
        "Heard Island and McDonald Islands": BigInt(280),
        "Kiribati": BigInt(280),
        "Marshall Islands": BigInt(280),
        "Micronesia": BigInt(280),
        "Nauru": BigInt(280),
        "New Caledonia": BigInt(280),
        "Niue": BigInt(280),
        "Norfolk Island": BigInt(280),
        "Northern Mariana Islands": BigInt(280),
        "Palau": BigInt(280),
        "Papua New Guinea": BigInt(280),
        "Pitcairn": BigInt(280),
        "Samoa": BigInt(210), // Preserved original custom rate baseline override
        "Solomon Islands": BigInt(280),
        "Tokelau": BigInt(280),
        "Tonga": BigInt(280),
        "Tuvalu": BigInt(280),
        "United States Minor Outlying Islands": BigInt(280),
        "Vanuatu": BigInt(280),
        "Wallis and Futuna": BigInt(280),

        // ==========================================
        // REGION 7: MIDDLE EAST ($300)
        // ==========================================
        "Bahrain": BigInt(300),
        "Iran": BigInt(300),
        "Iraq": BigInt(300),
        "Israel": BigInt(300),
        "Jordan": BigInt(300),
        "Kuwait": BigInt(300),
        "Lebanon": BigInt(300),
        "Oman": BigInt(300),
        "Palestine, State of": BigInt(300),
        "Qatar": BigInt(300),
        "Saudi Arabia": BigInt(300),
        "Syrian Arab Republic": BigInt(300),
        "United Arab Emirates": BigInt(300),
        "Yemen": BigInt(300),

        // ==========================================
        // REGION 8: AFRICA ($350)
        // ==========================================
        "Algeria": BigInt(350),
        "Angola": BigInt(350),
        "Antarctica": BigInt(350),
        "Benin": BigInt(350),
        "Botswana": BigInt(350),
        "Bouvet Island": BigInt(350),
        "Burkina Faso": BigInt(350),
        "Burundi": BigInt(350),
        "Cabo Verde": BigInt(350),
        "Cameroon": BigInt(350),
        "Central African Republic": BigInt(350),
        "Chad": BigInt(350),
        "Comoros": BigInt(350),
        "Congo, Democratic Republic of the": BigInt(350),
        "Congo, Republic of": BigInt(350),
        "Côte d'Ivoire": BigInt(350),
        "Djibouti": BigInt(350),
        "Egypt": BigInt(350),
        "Equatorial Guinea": BigInt(350),
        "Eritrea": BigInt(350),
        "Eswatini": BigInt(350),
        "Ethiopia": BigInt(350),
        "French Southern Territories": BigInt(350),
        "Gabon": BigInt(350),
        "Gambia": BigInt(350),
        "Ghana": BigInt(350),
        "Guinea": BigInt(350),
        "Guinea-Bissau": BigInt(350),
        "Kenya": BigInt(350),
        "Lesotho": BigInt(350),
        "Liberia": BigInt(350),
        "Libya": BigInt(350),
        "Madagascar": BigInt(350),
        "Malawi": BigInt(350),
        "Mali": BigInt(350),
        "Mauritania": BigInt(350),
        "Mauritius": BigInt(350),
        "Mayotte": BigInt(350),
        "Morocco": BigInt(350),
        "Mozambique": BigInt(350),
        "Namibia": BigInt(350),
        "Niger": BigInt(350),
        "Nigeria": BigInt(350),
        "Réunion": BigInt(350),
        "Rwanda": BigInt(350),
        "Saint Helena, Ascension and Tristan da Cunha": BigInt(350),
        "São Tomé and Príncipe": BigInt(350),
        "Senegal": BigInt(350),
        "Seychelles": BigInt(350),
        "Sierra Leone": BigInt(350),
        "Somalia": BigInt(350),
        "South Africa": BigInt(350),
        "South Sudan": BigInt(350),
        "Sudan": BigInt(350),
        "Tanzania": BigInt(350),
        "Togo": BigInt(350),
        "Tunisia": BigInt(350),
        "Uganda": BigInt(350),
        "Western Sahara": BigInt(350),
        "Zambia": BigInt(350),
        "Zimbabwe": BigInt(350)
      },
      baseDays: 180,
    },
}