export const genData = {
    LGE20KVA: {
      assetId: 120720,
      price: BigInt(15400),
      panel: {
        standard: { label: "120v Split Phase @60Hz", price: BigInt(0) },
        customized: { label: "Customize", price: BigInt(1_100) },
      },
      gridTie: {
        standard: { label: "Stand Alone", price: BigInt(0) },
        Rating225: { label: "Grid Tie (225amp Rating)", price: BigInt(3_850) },
        Rating400: { label: "Grid Tie (400amp Rating)", price: BigInt(5_500) },
        Rating630: { label: "Grid Tie (630amp Rating)", price: BigInt(11_000) },
      },
      monitoring: {
        standard: { label: "No Monitoring", price: BigInt(0) },
        customized: { label: "Monitoring", price: BigInt(2_200) },
      },
      countries: {
        USA: BigInt(180),
        Canada: BigInt(180),
        Mexico: BigInt(180),
        Bahamas: BigInt(180),
        Jamaica: BigInt(180),
        Haiti: BigInt(180),
        "Saint Lucia": BigInt(180),
        "Saint Vincent and the Grenadines": BigInt(180),
        Brazil: BigInt(250),
        Argentina: BigInt(250),
        Chile: BigInt(250),
        Germany: BigInt(220),
        France: BigInt(220),
        Italy: BigInt(220),
        UK: BigInt(230),
        Ireland: BigInt(230),
        India: BigInt(260),
        Singapore: BigInt(260),
        Malaysia: BigInt(260),
        China: BigInt(210),
        Simoa: BigInt(210),
        Fiji: BigInt(210),
        Austrailia: BigInt(280),
        "New Zealand": BigInt(280),
        UAE: BigInt(300),
        "Saudi Arabia": BigInt(300),
        Israel: BigInt(300),
        "South Africa": BigInt(350),
        Nigeria: BigInt(350),
        Egypt: BigInt(350),
      },
      baseDays: 90,
    },
    LGE45KVA: {
      assetId: 120745,
      price: BigInt(16500),
      panel: {
        standard: { label: "120v Split Phase @60Hz", price: BigInt(0) },
        customized: { label: "Customize", price: BigInt(1_100) },
      },
      gridTie: {
        standard: { label: "Stand Alone", price: BigInt(0) },
        Rating225: { label: "Grid Tie (225amp Rating)", price: BigInt(3_850) },
        Rating400: { label: "Grid Tie (400amp Rating)", price: BigInt(5_500) },
        Rating630: { label: "Grid Tie (630amp Rating)", price: BigInt(11_000) },
      },
      monitoring: {
        standard: { label: "No Monitoring", price: BigInt(0) },
        customized: { label: "Monitoring", price: BigInt(2_200) },
      },
      countries: {
        USA: BigInt(180),
        Canada: BigInt(180),
        Mexico: BigInt(180),
        Bahamas: BigInt(180),
        Jamaica: BigInt(180),
        Haiti: BigInt(180),
        "Saint Lucia": BigInt(180),
        "Saint Vincent and the Grenadines": BigInt(180),
        Brazil: BigInt(250),
        Argentina: BigInt(250),
        Chile: BigInt(250),
        Germany: BigInt(220),
        France: BigInt(220),
        Italy: BigInt(220),
        UK: BigInt(230),
        Ireland: BigInt(230),
        India: BigInt(260),
        Singapore: BigInt(260),
        Malaysia: BigInt(260),
        China: BigInt(210),
        Simoa: BigInt(210),
        Fiji: BigInt(210),
        Austrailia: BigInt(280),
        "New Zealand": BigInt(280),
        UAE: BigInt(300),
        "Saudi Arabia": BigInt(300),
        Israel: BigInt(300),
        "South Africa": BigInt(350),
        Nigeria: BigInt(350),
        Egypt: BigInt(350),
      },
      baseDays: 90,
    },
    LGE70KVA: {
      assetId: 120770,
      price: BigInt(17600),
      panel: {
        standard: { label: "120v Split Phase @60Hz", price: BigInt(0) },
        customized: { label: "Customize", price: BigInt(1_100) },
      },
      gridTie: {
        standard: { label: "Stand Alone", price: BigInt(0) },
        Rating225: { label: "Grid Tie (225amp Rating)", price: BigInt(3_850) },
        Rating400: { label: "Grid Tie (400amp Rating)", price: BigInt(5_500) },
        Rating630: { label: "Grid Tie (630amp Rating)", price: BigInt(11_000) },
      },
      monitoring: {
        standard: { label: "No Monitoring", price: BigInt(0) },
        customized: { label: "Monitoring", price: BigInt(2_200) },
      },
      countries: {
        USA: BigInt(180),
        Canada: BigInt(180),
        Mexico: BigInt(180),
        Bahamas: BigInt(180),
        Jamaica: BigInt(180),
        Haiti: BigInt(180),
        "Saint Lucia": BigInt(180),
        "Saint Vincent and the Grenadines": BigInt(180),
        Brazil: BigInt(250),
        Argentina: BigInt(250),
        Chile: BigInt(250),
        Germany: BigInt(220),
        France: BigInt(220),
        Italy: BigInt(220),
        UK: BigInt(230),
        Ireland: BigInt(230),
        India: BigInt(260),
        Singapore: BigInt(260),
        Malaysia: BigInt(260),
        China: BigInt(210),
        Simoa: BigInt(210),
        Fiji: BigInt(210),
        Austrailia: BigInt(280),
        "New Zealand": BigInt(280),
        UAE: BigInt(300),
        "Saudi Arabia": BigInt(300),
        Israel: BigInt(300),
        "South Africa": BigInt(350),
        Nigeria: BigInt(350),
        Egypt: BigInt(350),
      },
      baseDays: 90,
    },
    LGX100KVA: {
      assetId: 1207100,
      price: BigInt(47300),
      panel: {
        standard: { label: "480v 3-Phase @60Hz", price: BigInt(0) },
        customized: { label: "Customize", price: BigInt(1_100) },
      },
      gridTie: {
        standard: { label: "Stand Alone", price: BigInt(0) },
        Rating400: { label: "Grid Tie (400amp Rating)", price: BigInt(5_500) },
        Rating1260: { label: "Grid Tie (1260amp Rating)", price: BigInt(22_000) },
        Rating2100: { label: "Grid Tie (2100amp Rating)", price: BigInt(30_800) },
      },
      monitoring: {
        standard: { label: "No Monitoring", price: BigInt(0) },
        customized: { label: "Monitoring", price: BigInt(2_200) },
      },
      countries: {
        USA: BigInt(450),
        Canada: BigInt(450),
        Mexico: BigInt(450),
        Bahamas: BigInt(450),
        Jamaica: BigInt(450),
        Haiti: BigInt(450),
        "Saint Lucia": BigInt(450),
        "Saint Vincent and the Grenadines": BigInt(450),
        Brazil: BigInt(650),
        Argentina: BigInt(650),
        Chile: BigInt(650),
        Germany: BigInt(600),
        France: BigInt(600),
        Italy: BigInt(600),
        UK: BigInt(620),
        Ireland: BigInt(620),
        India: BigInt(700),
        Singapore: BigInt(700),
        Malaysia: BigInt(700),
        China: BigInt(580),
        Simoa: BigInt(580),
        Fiji: BigInt(580),
        Austrailia: BigInt(750),
        "New Zealand": BigInt(750),
        UAE: BigInt(800),
        "Saudi Arabia": BigInt(800),
        Israel: BigInt(800),
        "South Africa": BigInt(900),
        Nigeria: BigInt(900),
        Egypt: BigInt(900),
      },
      baseDays: 180,
    },
    LGX200KVA: {
      assetId: 1207200,
      price: BigInt(58300),
      panel: {
        standard: { label: "480v 3-Phase @60Hz", price: BigInt(0) },
        customized: { label: "Customize", price: BigInt(1_100) },
      },
      gridTie: {
        standard: { label: "Stand Alone", price: BigInt(0) },
        Rating400: { label: "Grid Tie (400amp Rating)", price: BigInt(5_500) },
        Rating1260: { label: "Grid Tie (1260amp Rating)", price: BigInt(22_000) },
        Rating2100: { label: "Grid Tie (2100amp Rating)", price: BigInt(30_800) },
      },
      monitoring: {
        standard: { label: "No Monitoring", price: BigInt(0) },
        customized: { label: "Monitoring", price: BigInt(2_200) },
      },
      countries: {
        USA: BigInt(450),
        Canada: BigInt(450),
        Mexico: BigInt(450),
        Bahamas: BigInt(450),
        Jamaica: BigInt(450),
        Haiti: BigInt(450),
        "Saint Lucia": BigInt(450),
        "Saint Vincent and the Grenadines": BigInt(450),
        Brazil: BigInt(650),
        Argentina: BigInt(650),
        Chile: BigInt(650),
        Germany: BigInt(600),
        France: BigInt(600),
        Italy: BigInt(600),
        UK: BigInt(620),
        Ireland: BigInt(620),
        India: BigInt(700),
        Singapore: BigInt(700),
        Malaysia: BigInt(700),
        China: BigInt(580),
        Simoa: BigInt(580),
        Fiji: BigInt(580),
        Austrailia: BigInt(750),
        "New Zealand": BigInt(750),
        UAE: BigInt(800),
        "Saudi Arabia": BigInt(800),
        Israel: BigInt(800),
        "South Africa": BigInt(900),
        Nigeria: BigInt(900),
        Egypt: BigInt(900),
      },
      baseDays: 180,
    },
    LGX300KVA: {
      assetId: 1207300,
      price: BigInt(69300),
      panel: {
        standard: { label: "480v 3-Phase @60Hz", price: BigInt(0) },
        customized: { label: "Customize", price: BigInt(1_100) },
      },
      gridTie: {
        standard: { label: "Stand Alone", price: BigInt(0) },
        Rating400: { label: "Grid Tie (400amp Rating)", price: BigInt(5_500) },
        Rating1260: { label: "Grid Tie (1260amp Rating)", price: BigInt(22_000) },
        Rating2100: { label: "Grid Tie (2100amp Rating)", price: BigInt(30_800) },
      },
      monitoring: {
        standard: { label: "No Monitoring", price: BigInt(0) },
        customized: { label: "Monitoring", price: BigInt(2_200) },
      },
      countries: {
        USA: BigInt(450),
        Canada: BigInt(450),
        Mexico: BigInt(450),
        Bahamas: BigInt(450),
        Jamaica: BigInt(450),
        Haiti: BigInt(450),
        "Saint Lucia": BigInt(450),
        "Saint Vincent and the Grenadines": BigInt(450),
        Brazil: BigInt(650),
        Argentina: BigInt(650),
        Chile: BigInt(650),
        Germany: BigInt(600),
        France: BigInt(600),
        Italy: BigInt(600),
        UK: BigInt(620),
        Ireland: BigInt(620),
        India: BigInt(700),
        Singapore: BigInt(700),
        Malaysia: BigInt(700),
        China: BigInt(580),
        Simoa: BigInt(580),
        Fiji: BigInt(580),
        Austrailia: BigInt(750),
        "New Zealand": BigInt(750),
        UAE: BigInt(800),
        "Saudi Arabia": BigInt(800),
        Israel: BigInt(800),
        "South Africa": BigInt(900),
        Nigeria: BigInt(900),
        Egypt: BigInt(900),
      },
      baseDays: 180,
    },
    LGX400KVA: {
      assetId: 1207400,
      price: BigInt(80300),
      panel: {
        standard: { label: "480v 3-Phase @60Hz", price: BigInt(0) },
        customized: { label: "Customize", price: BigInt(1_100) },
      },
      gridTie: {
        standard: { label: "Stand Alone", price: BigInt(0) },
        Rating400: { label: "Grid Tie (400amp Rating)", price: BigInt(5_500) },
        Rating1260: { label: "Grid Tie (1260amp Rating)", price: BigInt(22_0000) },
        Rating2100: { label: "Grid Tie (2100amp Rating)", price: BigInt(30_800) },
      },
      monitoring: {
        standard: { label: "No Monitoring", price: BigInt(0) },
        customized: { label: "Monitoring", price: BigInt(2_200) },
      },
      countries: {
        USA: BigInt(450),
        Canada: BigInt(450),
        Mexico: BigInt(450),
        Bahamas: BigInt(450),
        Jamaica: BigInt(450),
        Haiti: BigInt(450),
        "Saint Lucia": BigInt(450),
        "Saint Vincent and the Grenadines": BigInt(450),
        Brazil: BigInt(650),
        Argentina: BigInt(650),
        Chile: BigInt(650),
        Germany: BigInt(600),
        France: BigInt(600),
        Italy: BigInt(600),
        UK: BigInt(620),
        Ireland: BigInt(620),
        India: BigInt(700),
        Singapore: BigInt(700),
        Malaysia: BigInt(700),
        China: BigInt(580),
        Simoa: BigInt(580),
        Fiji: BigInt(580),
        Austrailia: BigInt(750),
        "New Zealand": BigInt(750),
        UAE: BigInt(800),
        "Saudi Arabia": BigInt(800),
        Israel: BigInt(800),
        "South Africa": BigInt(900),
        Nigeria: BigInt(900),
        Egypt: BigInt(900),
      },
      baseDays: 180,
    },
    LGX500KVA: {
      assetId: 1207500,
      price: BigInt(88000),
      panel: {
        standard: { label: "480v 3-Phase @60Hz", price: BigInt(0) },
        customized: { label: "Customize", price: BigInt(1_100) },
      },
      gridTie: {
        standard: { label: "Stand Alone", price: BigInt(0) },
        Rating400: { label: "Grid Tie (400amp Rating)", price: BigInt(5_500) },
        Rating1260: { label: "Grid Tie (1260amp Rating)", price: BigInt(22_000) },
        Rating2100: { label: "Grid Tie (2100amp Rating)", price: BigInt(30_800) },
      },
      monitoring: {
        standard: { label: "No Monitoring", price: BigInt(0) },
        customized: { label: "Monitoring", price: BigInt(2_200) },
      },
      countries: {
        USA: BigInt(450),
        Canada: BigInt(450),
        Mexico: BigInt(450),
        Bahamas: BigInt(450),
        Jamaica: BigInt(450),
        Haiti: BigInt(450),
        "Saint Lucia": BigInt(450),
        "Saint Vincent and the Grenadines": BigInt(450),
        Brazil: BigInt(650),
        Argentina: BigInt(650),
        Chile: BigInt(650),
        Germany: BigInt(600),
        France: BigInt(600),
        Italy: BigInt(600),
        UK: BigInt(620),
        Ireland: BigInt(620),
        India: BigInt(700),
        Singapore: BigInt(700),
        Malaysia: BigInt(700),
        China: BigInt(580),
        Simoa: BigInt(580),
        Fiji: BigInt(580),
        Austrailia: BigInt(750),
        "New Zealand": BigInt(750),
        UAE: BigInt(800),
        "Saudi Arabia": BigInt(800),
        Israel: BigInt(800),
        "South Africa": BigInt(900),
        Nigeria: BigInt(900),
        Egypt: BigInt(900),
      }
    },
    LGX60OKVA: {
      assetId: 1207600,
      price: BigInt(99000),
      panel: {
        standard: { label: "480v 3-Phase @60Hz", price: BigInt(0) },
        customized: { label: "Customize", price: BigInt(1_100) },
      },
      gridTie: {
        standard: { label: "Stand Alone", price: BigInt(0) },
        Rating400: { label: "Grid Tie (400amp Rating)", price: BigInt(5_500) },
        Rating1260: { label: "Grid Tie (1260amp Rating)", price: BigInt(22_000) },
        Rating2100: { label: "Grid Tie (2100amp Rating)", price: BigInt(30_800) },
      },
      monitoring: {
        standard: { label: "No Monitoring", price: BigInt(0) },
        customized: { label: "Monitoring", price: BigInt(2_200) },
      },
      countries: {
        USA: BigInt(450),
        Canada: BigInt(450),
        Mexico: BigInt(450),
        Bahamas: BigInt(450),
        Jamaica: BigInt(450),
        Haiti: BigInt(450),
        "Saint Lucia": BigInt(450),
        "Saint Vincent and the Grenadines": BigInt(450),
        Brazil: BigInt(650),
        Argentina: BigInt(650),
        Chile: BigInt(650),
        Germany: BigInt(600),
        France: BigInt(600),
        Italy: BigInt(600),
        UK: BigInt(620),
        Ireland: BigInt(620),
        India: BigInt(700),
        Singapore: BigInt(700),
        Malaysia: BigInt(700),
        China: BigInt(580),
        Simoa: BigInt(580),
        Fiji: BigInt(580),
        Austrailia: BigInt(750),
        "New Zealand": BigInt(750),
        UAE: BigInt(800),
        "Saudi Arabia": BigInt(800),
        Israel: BigInt(800),
        "South Africa": BigInt(900),
        Nigeria: BigInt(900),
        Egypt: BigInt(900),
      },
      baseDays: 180,
    },
}